CREATE TABLE public.grand_fleet_bonus_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),clan_id uuid NOT NULL,member_id uuid NOT NULL,leader_id uuid NOT NULL,asset text NOT NULL,source_type text NOT NULL,source_id text NOT NULL,reward_amount numeric NOT NULL,bonus_amount numeric NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(member_id,asset,source_type,source_id));
GRANT ALL ON public.grand_fleet_bonus_ledger TO service_role;
REVOKE ALL ON public.grand_fleet_bonus_ledger FROM anon,authenticated;
ALTER TABLE public.grand_fleet_bonus_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY service_only ON public.grand_fleet_bonus_ledger FOR ALL TO service_role USING(true) WITH CHECK(true);
CREATE FUNCTION public.grand_fleet_bonus_amount(p_amount numeric) RETURNS numeric LANGUAGE sql IMMUTABLE SET search_path=public AS $$SELECT CASE WHEN p_amount>0 THEN p_amount*0.05 ELSE 0 END$$;
REVOKE ALL ON FUNCTION public.grand_fleet_bonus_amount(numeric) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.grand_fleet_bonus_amount(numeric) TO service_role;
CREATE FUNCTION public.grand_fleet_credit_bonus(p_member uuid,p_asset text,p_amount numeric,p_type text,p_source text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE c public.clans%rowtype; bonus numeric; record_id uuid; before_balance numeric; BEGIN
IF p_amount IS NULL OR p_amount<=0 OR p_source IS NULL OR p_type NOT IN('realm_expedition_claim','realm_bounty_claim','realm_explore_finish','realm_ruin_finish','claim_daily_quest','clan_boss_deliver','clan_war_settle','distribute_global_boss_rewards','expedition','explore_extract','explore_finish','explore_complete','explore_victory','ruin_room','ruin_clear','ruin_extract') THEN RETURN; END IF;
IF p_asset<>'BERRIES' AND NOT EXISTS(SELECT 1 FROM public.realm_materials WHERE id=p_asset AND enabled) THEN RETURN; END IF;
SELECT f.* INTO c FROM public.clans f JOIN public.clan_members m ON m.clan_id=f.id WHERE m.user_id=p_member AND NOT f.suspended;
IF c.id IS NULL OR c.leader_user_id=p_member OR NOT EXISTS(SELECT 1 FROM public.clan_members WHERE clan_id=c.id AND user_id=c.leader_user_id AND role='leader') THEN RETURN; END IF;
IF EXISTS(SELECT 1 FROM public.game_players WHERE id IN(p_member,c.leader_user_id) AND banned) THEN RETURN; END IF;
bonus:=public.grand_fleet_bonus_amount(p_amount);
INSERT INTO public.grand_fleet_bonus_ledger(clan_id,member_id,leader_id,asset,source_type,source_id,reward_amount,bonus_amount) VALUES(c.id,p_member,c.leader_user_id,p_asset,p_type,p_source,p_amount,bonus) ON CONFLICT DO NOTHING RETURNING id INTO record_id;
IF record_id IS NULL THEN RETURN; END IF;
IF p_asset='BERRIES' THEN SELECT forge_coins INTO before_balance FROM public.game_players WHERE id=c.leader_user_id FOR UPDATE; UPDATE public.game_players SET forge_coins=forge_coins+bonus,updated_at=now() WHERE id=c.leader_user_id; INSERT INTO public.wallet_ledger(user_id,type,amount_fc,balance_before,balance_after,reference_id) VALUES(c.leader_user_id,'grand_fleet_bonus',bonus,before_balance,before_balance+bonus,record_id::text);
ELSE PERFORM public.realm_material_add(c.leader_user_id,p_asset,bonus,'grand_fleet_bonus',record_id::text); END IF; END$$;
REVOKE ALL ON FUNCTION public.grand_fleet_credit_bonus(uuid,text,numeric,text,text) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.grand_fleet_credit_bonus(uuid,text,numeric,text,text) TO service_role;
CREATE FUNCTION public.grand_fleet_material_bonus_trigger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$BEGIN PERFORM public.grand_fleet_credit_bonus(NEW.user_id,NEW.material_id,NEW.amount,NEW.reason,NEW.id::text); RETURN NEW; END$$;
REVOKE ALL ON FUNCTION public.grand_fleet_material_bonus_trigger() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER grand_fleet_material_bonus AFTER INSERT ON public.realm_material_ledger FOR EACH ROW EXECUTE FUNCTION public.grand_fleet_material_bonus_trigger();
DO $$DECLARE fn record; def text; patched text; uid text; BEGIN FOR fn IN SELECT oid,proname FROM pg_proc WHERE pronamespace='public'::regnamespace AND prokind='f' AND proname IN('realm_expedition_claim','realm_bounty_claim','realm_explore_finish','realm_ruin_finish','claim_daily_quest','clan_boss_deliver','clan_war_settle','distribute_global_boss_rewards') LOOP
 def:=pg_get_functiondef(fn.oid); uid:=CASE WHEN fn.proname='claim_daily_quest' THEN 'u' WHEN fn.proname='clan_boss_deliver' THEN 'p_user_id' WHEN fn.proname IN('clan_war_settle','distribute_global_boss_rewards') THEN 'r.user_id' ELSE 'p_user' END;
 patched:=regexp_replace(def,'(UPDATE\s+(?:public\.)?game_players\s+SET\s+forge_coins\s*=\s*forge_coins\s*\+[^;]*;)',E'\\1\n PERFORM public.grand_fleet_credit_bonus('||uid||',''BERRIES'','||CASE WHEN fn.proname='claim_daily_quest' THEN 'q.reward_fc' WHEN fn.proname='distribute_global_boss_rewards' THEN 'v_reward' ELSE 'v_fc' END||','''||fn.proname||''',txid_current()::text||'':''||'''||fn.proname||'''||'':''||'||uid||'::text);','i');
 IF patched=def THEN RAISE EXCEPTION 'Missing gameplay credit hook: %',fn.proname; END IF; EXECUTE patched; END LOOP; END$$;
CREATE FUNCTION public.grand_fleet_bonus_state(p_telegram_id bigint) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE uid uuid; fleet uuid; BEGIN uid:=public.clan_resolve_user(p_telegram_id); SELECT clan_id INTO fleet FROM public.clan_members WHERE user_id=uid; RETURN jsonb_build_object('rate',0.05,'berries',COALESCE((SELECT sum(bonus_amount) FROM public.grand_fleet_bonus_ledger WHERE leader_id=uid AND clan_id=fleet AND asset='BERRIES'),0),'materials',COALESCE((SELECT jsonb_object_agg(asset,total) FROM(SELECT asset,sum(bonus_amount) total FROM public.grand_fleet_bonus_ledger WHERE leader_id=uid AND clan_id=fleet AND asset<>'BERRIES' GROUP BY asset)x),'{}'::jsonb)); END$$;
REVOKE ALL ON FUNCTION public.grand_fleet_bonus_state(bigint) FROM PUBLIC,anon,authenticated; GRANT EXECUTE ON FUNCTION public.grand_fleet_bonus_state(bigint) TO service_role;