import{useTonConnectUI,useTonWallet}from'@tonconnect/ui-react';
import{useMutation,useQueryClient}from'@tanstack/react-query';
import{ArrowLeft,Check,Lock,ScrollText,Star}from'lucide-react';
import{toast}from'sonner';
import{createSeasonPassOrder,seasonPassRequest}from'../services';
import{useSeasonPass}from'../hooks';
import{mainScreenArt}from'../gameAssets';
import{progressPercent,type PassReward,type PassTier}from'../seasonPass';

const art:Record<string,string>={fc:'/assets/game/coins/forge-coin.png',pet_food:'/assets/game/ui/season-pet-food.png',fragments:'/assets/game/ui/season-fragments.png',pvp_ticket:'/assets/game/ui/season-pvp-ticket.png',skin:'/assets/game/ui/season-skin.png',pet_egg:'/assets/game/pet-eggs/rare-egg.webp',hero_chest:'/assets/game/chests/epic-chest.png','season-1-aldren':'/assets/game/heroes/season-1-aldren.png','season-1-mythic-egg':'/assets/game/pet-eggs/season-1-mythic-egg.png'};

export function SeasonPassPage({telegramInitData,onClose,onMissions}:{telegramInitData:string;onClose:()=>void;onMissions:()=>void}){
 const[tonUI]=useTonConnectUI(),wallet=useTonWallet(),q=useQueryClient(),{data,isLoading,error,refetch}=useSeasonPass(telegramInitData,true);
 const purchase=useMutation({mutationFn:async(tier:PassTier)=>{if(!wallet){await tonUI.openModal();throw Error('Conecte sua carteira TON e tente novamente.')}const order=await createSeasonPassOrder(telegramInitData,tier);await tonUI.sendTransaction({validUntil:Math.floor(Date.now()/1000)+300,messages:[{address:order.paymentAddress,amount:order.amountNano}]});return order},onSuccess:async()=>{await Promise.all([['season-pass'],['season-pass-rewards'],['season-pass-profile'],['wallet-history'],['notifications'],['missions']].map(queryKey=>q.invalidateQueries({queryKey})));toast.success('Pagamento enviado. O Passe será liberado após confirmação.')},onError:e=>toast.error(e instanceof Error?e.message:'Falha ao comprar o Passe.')});
 const claim=useMutation({mutationFn:(rewardId:string)=>seasonPassRequest(telegramInitData,'claim',{rewardId}),onSuccess:dashboard=>{q.setQueryData(['season-pass',telegramInitData],dashboard);toast.success('Recompensa coletada!')},onError:e=>toast.error(e instanceof Error?e.message:'Falha ao coletar.')});
 if(isLoading)return<Shell onClose={onClose}><div className="space-y-3 pt-12">{[1,2,3].map(x=><div key={x} className="h-24 animate-pulse rounded-2xl bg-white/5"/>)}<p className="text-center text-sm text-amber-200">Preparando a temporada...</p></div></Shell>;
 if(error||!data)return<Shell onClose={onClose}><div className="py-24 text-center"><p>Não foi possível carregar o Passe da Temporada.</p><button onClick={()=>void refetch()} className="mt-4 rounded-xl border border-amber-300/30 px-5 py-3">TENTAR NOVAMENTE</button></div></Shell>;
 const remaining=Math.max(0,new Date(data.season.endsAt).getTime()-Date.now()),days=Math.floor(remaining/86400000),hours=Math.floor(remaining%86400000/3600000),currentXp=data.player.xp%data.season.xpPerLevel;
 return<Shell onClose={onClose}>
  <section className="rounded-3xl border border-amber-300/25 bg-gradient-to-br from-[#17223a] to-black p-4"><div className="flex items-center gap-3"><img src={mainScreenArt.seasonPass} className="h-20 w-20 object-contain"/><div><p className="text-[10px] uppercase tracking-[.25em] text-amber-300">{data.season.name}</p><h2 className="text-2xl font-black">PASSE DA TEMPORADA</h2><p className="text-xs text-slate-400">Tempo restante: {days}d {hours}h</p></div></div><div className="mt-3 flex justify-between text-xs"><b>Nível {data.player.level}</b><span>{currentXp}/{data.season.xpPerLevel} XP</span></div><div className="mt-1 h-3 overflow-hidden rounded-full bg-black/60"><div className="h-full bg-gradient-to-r from-amber-500 to-yellow-200 transition-all" style={{width:`${progressPercent(data.player.xp,data.season.xpPerLevel)}%`}}/></div><button onClick={onMissions} className="mt-3 rounded-xl border border-amber-300/30 px-4 py-2 text-xs font-bold">MISSÕES</button></section>
  <div className="mt-3 grid grid-cols-2 gap-2"><Pass tier="adventurer" owned={data.player.adventurerOwned} disabled={data.player.legendaryOwned} price={data.season.adventurerPriceTon} pending={purchase.isPending} onBuy={()=>purchase.mutate('adventurer')}/><Pass tier="legendary" owned={data.player.legendaryOwned} price={data.player.adventurerOwned?data.season.upgradePriceTon:data.season.legendaryPriceTon} upgrade={data.player.adventurerOwned&&!data.player.legendaryOwned} pending={purchase.isPending} onBuy={()=>purchase.mutate('legendary')}/></div>
  <p className="mt-3 rounded-xl border border-amber-300/15 bg-black/40 p-3 text-center text-[10px] text-amber-100">O Passe Lendário também libera todas as recompensas do Passe Aventureiro.</p>{data.player.tier==='none'?<p className="mt-2 text-center text-xs text-slate-300">Compre um passe para liberar as recompensas da temporada.</p>:null}
  <section className="mt-4 overflow-hidden rounded-3xl border border-amber-300/30 bg-gradient-to-b from-[#0b1220] to-black shadow-[0_0_30px_rgba(0,0,0,.6)]">
   <div className="sticky top-0 z-20 grid grid-cols-[68px_1fr_1fr] items-end gap-1 border-b border-amber-300/20 bg-[#080d16]/95 px-2 py-3 backdrop-blur">
    <div className="text-center"><b className="block text-[11px] font-black uppercase tracking-[.14em] text-amber-300">NÍVEL</b><span className="mx-auto mt-1 block h-px w-8 bg-amber-300/50"/></div>
    <div className="border-l border-amber-300/15 text-center"><b className="block text-[10px] font-black uppercase leading-tight tracking-[.1em] text-emerald-300">PASSE<br/>AVENTUREIRO</b><span className="mx-auto mt-1 block h-px w-10 bg-emerald-300/50"/></div>
    <div className="border-l border-amber-300/15 text-center"><b className="block text-[10px] font-black uppercase leading-tight tracking-[.1em] text-violet-300">PASSE<br/>LENDÁRIO</b><span className="mx-auto mt-1 block h-px w-10 bg-violet-300/50"/></div>
   </div>
   <div className="divide-y divide-white/5">
    {Array.from({length:30},(_,i)=>{const level=i+1;const reached=data.player.level>=level;return<div key={level} className={`grid grid-cols-[68px_1fr_1fr] items-stretch gap-1 px-2 py-2 ${reached?'bg-amber-400/[.04]':''}`}>
     <div className="grid place-items-center text-center"><span className={`grid h-9 w-9 place-items-center rounded-full border text-[11px] font-black ${reached?'border-amber-300/70 bg-amber-400/15 text-amber-200':'border-white/10 bg-black/40 text-slate-500'}`}>{level}</span></div>
     {(['adventurer','legendary'] as PassTier[]).map(tier=><Reward key={tier} reward={data.rewards.find(x=>x.level===level&&x.tier===tier)} pending={claim.isPending} onClaim={id=>claim.mutate(id)}/>)}
    </div>})}
   </div>
  </section>
 </Shell>
}

function Reward({reward:r,pending,onClaim}:{reward?:PassReward;pending:boolean;onClaim:(id:string)=>void}){const exclusive=Boolean(r?.code&&art[r.code]);return<button disabled={!r?.unlocked||r.claimed||pending} onClick={()=>r&&onClaim(r.id)} className={`relative min-h-24 overflow-hidden rounded-xl border p-2 text-center text-[8px] ${exclusive?'border-amber-300/70 bg-gradient-to-b from-violet-950/70 to-amber-950/30 shadow-[0_0_18px_rgba(251,191,36,.22)]':r?.claimed?'border-emerald-400/35 bg-emerald-500/10':r?.unlocked?'border-amber-300/35 bg-amber-500/10':'border-white/5 bg-white/[.02] text-slate-600'}`}>{exclusive?<span className="absolute left-1 top-1 rounded-full border border-amber-200/40 bg-black/70 px-1.5 py-0.5 text-[5px] font-black text-amber-200">EXCLUSIVO</span>:null}{r?.claimed?<Check className="mx-auto h-5 w-5"/>:r?<><img src={art[r.code??'']??art[r.type]??art.fragments} alt={r.title} className={`mx-auto h-11 w-11 object-contain drop-shadow-[0_0_8px_rgba(251,191,36,.35)] ${r.unlocked?'':'grayscale opacity-35'}`}/>{!r.unlocked?<Lock className="absolute right-1 top-1 h-3 w-3 text-slate-500"/>:null}</>:null}<span className="mt-1 block leading-tight">{r?.title}</span>{r&&!r.unlocked?<span className="mt-1 block text-[7px] text-slate-500">Compre um passe</span>:null}</button>}
function Shell({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return<div className="fullscreen-page text-white"><div className="mx-auto min-h-full w-full max-w-[480px] p-3"><header className="flex items-center justify-between"><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-amber-300/25 bg-black/50"><ArrowLeft/></button><div className="text-center"><p className="text-[9px] tracking-[.28em] text-amber-300">FORGE VILLAGE</p><b>PASSE DA TEMPORADA</b></div><ScrollText className="text-amber-300"/></header>{children}</div></div>}
function Pass({tier,owned,disabled=false,upgrade=false,price,pending,onBuy}:{tier:'adventurer'|'legendary';owned:boolean;disabled?:boolean;upgrade?:boolean;price:number;pending:boolean;onBuy:()=>void}){return<div className={`rounded-2xl border p-3 text-center ${tier==='adventurer'?'border-emerald-400/30 bg-emerald-950/20':'border-violet-400/35 bg-violet-950/25'}`}><Star className={`mx-auto ${tier==='adventurer'?'text-emerald-300':'text-amber-300'}`}/><b className="mt-1 block text-xs">PASSE {tier==='adventurer'?'AVENTUREIRO':'LENDÁRIO'}</b><p className="text-lg font-black">{price} TON</p><button disabled={owned||disabled||pending} onClick={onBuy} className="mt-2 w-full rounded-xl bg-amber-400 py-2 text-[9px] font-black text-black disabled:bg-emerald-500">{owned||disabled?'ATIVO':upgrade?'UPGRADE PARA LENDÁRIO':'COMPRAR PASSE'}</button></div>}
