import { OceanControl } from './OceanControl';
import { petRarityLabel } from '../petLabels';
import{isNftExclusivePet}from'../petLabels';import{useEffect,useMemo,useRef,useState}from'react';import{Check,Star,Zap}from'lucide-react';import type{PetRarity}from'../petRules';import type{PlayerPet}from'../pets';import{useT}from'../LanguageContext';import{petBuffShortLabel}from'../petLabels';import{petBuffIcon}from'./PetBuff';
export type EggOpeningPhase='idle'|'entering'|'floating'|'shaking'|'cracking'|'burst'|'revealing'|'result';
export const PET_REVEAL_THEME={common:{primary:'#9ca3af',secondary:'#f8fafc',glow:'rgba(156,163,175,.45)',label:'COMMON',particles:15},uncommon:{primary:'#22c55e',secondary:'#86efac',glow:'rgba(34,197,94,.50)',label:'UNCOMMON',particles:25},rare:{primary:'#38bdf8',secondary:'#93c5fd',glow:'rgba(56,189,248,.55)',label:'RARE',particles:35},epic:{primary:'#a855f7',secondary:'#d8b4fe',glow:'rgba(168,85,247,.60)',label:'EPIC',particles:44},legendary:{primary:'#facc15',secondary:'#fde68a',glow:'rgba(250,204,21,.70)',label:'LEGENDARY',particles:52},mythic:{primary:'#8b5cf6',secondary:'#67e8f9',glow:'rgba(139,92,246,.78)',label:'MYTHIC',particles:58},ancestral:{primary:'#ef4444',secondary:'#fbbf24',glow:'rgba(239,68,68,.78)',label:'ANCESTRAL',particles:58},exclusive:{primary:'#f0abfc',secondary:'#fdf4ff',glow:'rgba(240,171,252,.80)',label:'EXCLUSIVE',particles:60},nft_exclusive:{primary:'#22d3ee',secondary:'#a78bfa',glow:'rgba(34,211,238,.85)',label:'NFT EXCLUSIVE',particles:64},celestial:{primary:'#f8fafc',secondary:'#facc15',glow:'rgba(250,204,21,.92)',label:'CELESTIAL',particles:72}}as const;
export type EggRevealResult={name:string;rarity:PetRarity;image:string;duplicateFragments:number;resultType?:'new_pet'|'duplicate';playerPetId?:string};
const phases:Array<[EggOpeningPhase,number]>=[['entering',0],['floating',900],['shaking',2900],['cracking',4100],['burst',7200],['revealing',7900],['result',9400]];
export function PetEggOpeningOverlay({result,eggImage,pet,onContinue,onActivate}:{result:EggRevealResult;eggImage:string;pet?:PlayerPet;onContinue:()=>void;onActivate?:()=>void}){const t=useT(),[phase,setPhase]=useState<EggOpeningPhase>('idle'),[canSkip,setCanSkip]=useState(false),[imageFailed,setImageFailed]=useState(false),theme=PET_REVEAL_THEME[(isNftExclusivePet({...result,...(pet??{})}) ? 'nft_exclusive' : result.rarity) as PetRarity]??PET_REVEAL_THEME.common,reduced=useMemo(()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false,[]),bonus=pet?Object.entries(pet.buffs)[0] as [string,number]|undefined:undefined,continueRef=useRef(onContinue);continueRef.current=onContinue;
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';const timers=(reduced?[['entering',0],['revealing',250],['result',700]]as Array<[EggOpeningPhase,number]>:phases).map(([next,delay])=>window.setTimeout(()=>setPhase(next),delay)),skip=window.setTimeout(()=>setCanSkip(true),reduced?300:2500),failsafe=window.setTimeout(()=>setPhase('result'),12000),back=window.Telegram?.WebApp?.BackButton,block=()=>{};back?.onClick(block);return()=>{timers.forEach(clearTimeout);clearTimeout(skip);clearTimeout(failsafe);document.body.style.overflow=previous;back?.offClick(block)}},[reduced]);
  useEffect(()=>{const webApp=window.Telegram?.WebApp as unknown as {HapticFeedback?:{impactOccurred:(style:'light'|'heavy')=>void}}|undefined,haptic=webApp?.HapticFeedback;if(phase==='cracking')haptic?.impactOccurred('light');if(phase==='burst')haptic?.impactOccurred('heavy')},[phase]);
 const final=phase==='result',revealing=phase==='revealing'||final,particleCount=Math.min(theme.particles,window.innerWidth<380?32:theme.particles),
  // The backend states the outcome explicitly; fragments are only a fallback for legacy payloads.
  isDuplicate=result.resultType?result.resultType==='duplicate':result.duplicateFragments>0;
  return <div className={`pet-egg-overlay mascot-chest-overlay phase-${phase}`} style={{'--pet-primary':theme.primary,'--pet-secondary':theme.secondary,'--pet-glow':theme.glow}as React.CSSProperties}><div className="pet-egg-backdrop"/><div className="pet-egg-particles" aria-hidden>{Array.from({length:particleCount},(_,i)=><i key={i} style={{'--particle-index':i,'--particle-angle':`${i/particleCount*360}deg`,'--particle-delay':`${(i%9)*-.13}s`}as React.CSSProperties}/>)}</div>{canSkip&&!final?<OceanControl type="button" className="pet-egg-skip" onClick={()=>setPhase('result')}>{t('pets.skip')}</OceanControl>:null}<main className="pet-egg-stage"><div className="pet-egg-glow"/>{!revealing?<div className="pet-egg-shell"><img src={eggImage} alt={t('pets.eggAlt')} className="pet-egg-image mascot-chest-base"/><img src={eggImage} alt="" aria-hidden className="pet-egg-image mascot-chest-lid"/><div className="mascot-chest-light" aria-hidden/></div>:null}<div className="pet-light-burst"/>{revealing?<section className="pet-reveal-creature">{imageFailed?<div className="pet-reveal-fallback"><Zap/></div>:<img src={result.image} alt={result.name} onError={()=>setImageFailed(true)}/>}<h1>{result.name}</h1><p className="pet-reveal-rarity">{petRarityLabel(result.rarity)}</p><p className="pet-reveal-kicker">{isDuplicate?t('pets.duplicateFragments'):t('pets.newPet')}</p>{isDuplicate?<div className="pet-reveal-bonus"><Star/><span>{t('pets.fragmentsReceived')}</span><strong>+{result.duplicateFragments}</strong></div>:<Bonus bonus={bonus}/>}<div className="pet-reveal-actions">{onActivate&&!isDuplicate?<OceanControl type="button" onClick={onActivate}><Check/>{t('pets.activateNow')}</OceanControl>:null}<OceanControl type="button" onClick={onContinue}>{t('pets.continue').toUpperCase()}</OceanControl></div></section>:null}</main></div>}
function Bonus({bonus}:{bonus?:[string,number]}){const t=useT(),key=bonus?.[0]??'';return<div className="pet-reveal-bonus">{petBuffIcon(key)}<span>{key?petBuffShortLabel(key):t('pets.mainBonus')}</span><strong>+{bonus?.[1]??0}%</strong></div>}
