import{useEffect,useMemo,useState}from'react';import{Check,Flame,Heart,Shield,Star,Zap}from'lucide-react';import type{PetRarity}from'../petRules';import type{PlayerPet}from'../pets';
export type EggOpeningPhase='idle'|'entering'|'floating'|'shaking'|'cracking'|'burst'|'revealing'|'result';
export const PET_REVEAL_THEME={common:{primary:'#9ca3af',secondary:'#d1d5db',glow:'rgba(156,163,175,.45)',label:'COMUM',particles:15},uncommon:{primary:'#22c55e',secondary:'#86efac',glow:'rgba(34,197,94,.50)',label:'INCOMUM',particles:25},rare:{primary:'#38bdf8',secondary:'#93c5fd',glow:'rgba(56,189,248,.55)',label:'RARO',particles:35},epic:{primary:'#a855f7',secondary:'#d8b4fe',glow:'rgba(168,85,247,.60)',label:'ÉPICO',particles:50},legendary:{primary:'#facc15',secondary:'#fde68a',glow:'rgba(250,204,21,.70)',label:'LENDÁRIO',particles:65}}as const;
export type EggRevealResult={name:string;rarity:PetRarity;image:string;duplicateFragments:number};
const phases:Array<[EggOpeningPhase,number]>=[['entering',0],['floating',700],['shaking',1700],['cracking',3000],['burst',4200],['revealing',4800],['result',6200]];
export function PetEggOpeningOverlay({result,eggImage,pet,onContinue,onActivate}:{result:EggRevealResult;eggImage:string;pet?:PlayerPet;onContinue:()=>void;onActivate?:()=>void}){const[phase,setPhase]=useState<EggOpeningPhase>('idle'),[canSkip,setCanSkip]=useState(false),[imageFailed,setImageFailed]=useState(false),theme=PET_REVEAL_THEME[result.rarity]??PET_REVEAL_THEME.common,reduced=useMemo(()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false,[]),bonus=pet?Object.entries(pet.buffs)[0] as [string,number]|undefined:undefined;
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';const timers=(reduced?[['entering',0],['revealing',250],['result',700]]as Array<[EggOpeningPhase,number]>:phases).map(([next,delay])=>window.setTimeout(()=>setPhase(next),delay)),skip=window.setTimeout(()=>setCanSkip(true),reduced?300:2000),back=window.Telegram?.WebApp?.BackButton,block=()=>{};back?.offClick(onContinue);back?.onClick(block);return()=>{timers.forEach(clearTimeout);clearTimeout(skip);document.body.style.overflow=previous;back?.offClick(block)}},[onContinue,reduced]);
 const final=phase==='result',revealing=phase==='revealing'||final,particleCount=Math.min(theme.particles,window.innerWidth<380?32:theme.particles);
 return <div className={`pet-egg-overlay phase-${phase}`} style={{'--pet-primary':theme.primary,'--pet-secondary':theme.secondary,'--pet-glow':theme.glow}as React.CSSProperties}><div className="pet-egg-backdrop"/><div className="pet-egg-particles" aria-hidden>{Array.from({length:particleCount},(_,i)=><i key={i} style={{'--particle-index':i,'--particle-angle':`${i/particleCount*360}deg`,'--particle-delay':`${(i%9)*-.13}s`}as React.CSSProperties}/>)}</div>{canSkip&&!final?<button type="button" className="pet-egg-skip" onClick={()=>setPhase('result')}>PULAR</button>:null}<main className="pet-egg-stage"><div className="pet-egg-magic-circle"/><div className="pet-egg-glow"/>{!revealing?<div className="pet-egg-shell"><img src={eggImage} alt="Ovo" className="pet-egg-image"/><svg className="pet-egg-cracks" viewBox="0 0 100 140" aria-hidden><path d="M52 16 44 43l12 8-17 22 13 12-19 31M55 51l17-13M51 85l23 17"/></svg></div>:null}<div className="pet-light-burst"/>{revealing?<section className="pet-reveal-creature"><p className="pet-reveal-kicker">{result.duplicateFragments>0?'DUPLICATA CONVERTIDA':'NOVO COMPANHEIRO'}</p>{imageFailed?<div className="pet-reveal-fallback"><Zap/></div>:<img src={result.image} alt={result.name} onError={()=>setImageFailed(true)}/>}<h1>{result.name}</h1><p className="pet-reveal-rarity">{theme.label}</p><p className="pet-reveal-level">Nv. {pet?.level??1} · Poder {pet?.power?.toLocaleString()??'--'}</p>{result.duplicateFragments>0?<div className="pet-reveal-bonus"><Star/><span>Fragmentos recebidos</span><strong>+{result.duplicateFragments}</strong></div>:<Bonus bonus={bonus}/>}<div className="pet-reveal-actions">{onActivate&&result.duplicateFragments===0?<button type="button" onClick={onActivate}><Check/>ATIVAR AGORA</button>:null}<button type="button" onClick={onContinue}>CONTINUAR</button></div></section>:null}</main></div>}
function Bonus({bonus}:{bonus?:[string,number]}){const key=bonus?.[0]??'',icons:Record<string,React.ReactNode>={boss_damage_percent:<Flame/>,team_hp_percent:<Heart/>,pvp_defense_percent:<Shield/>,drop_chance_percent:<Star/>},labels:Record<string,string>={boss_damage_percent:'Dano contra chefe',team_hp_percent:'HP da equipe',pvp_defense_percent:'Defesa PvP',drop_chance_percent:'Chance de saque'};return<div className="pet-reveal-bonus">{icons[key]??<Zap/>}<span>{labels[key]??(key.replace(/_/g,' ')||'Bônus principal')}</span><strong>+{bonus?.[1]??0}%</strong></div>}
