export type PoolRankEntry={position:number;playerId:string;name:string;avatarUrl:string|null;points:number;eligible:boolean;estimatedPrizeTon:number;raffleWeight?:number};
export type PoolHistoryEntry={id:string;weekLabel:string;amountTon:number;winnerCount:number;playerRewardTon:number;distributedAt:string};
export type PoolEligibility={points:number;minimumPoints:number;ownedHeroes:number;minimumHeroes:number;pointsEligible:boolean;heroesEligible:boolean;banned?:boolean;eligible:boolean};
export type CommunityPoolDashboard={season:{id:string;weekLabel:string;balanceTon:number;startsAt:string;endsAt:string;status:'active'|'distributing'|'distributed'|'cancelled';rankingPoolTon?:number;rafflePoolTon?:number};player:{points:number;position:number|null;eligible:boolean;walletConnected:boolean;accountAgeDays:number;hasHero:boolean;ownedHeroes?:number;pointsEligible?:boolean;heroesEligible?:boolean;estimatedRewardTon?:number};eligibility?:PoolEligibility;settings:{minimumPoints:number;minimumHeroes?:number;rankingSharePercent:number;lotterySharePercent:number};participantCount:number;ranking:PoolRankEntry[];history:PoolHistoryEntry[]};

export const POOL_POINT_DEFAULTS={daily_login:10,daily_mission:20,weekly_mission:100,boss_defeat:40,pvp_win:25,ad_watch:5,season_pass_purchase:300,egg_purchase:80,hero_purchase:60,pet_purchase:80}as const;
export const POOL_REVENUE_DEFAULTS={season_pass:5,egg:5,pet:4,hero:3,fc_purchase:2,event:0,ad:0}as const;
export const COMMUNITY_POOL_PERCENT=15;
export type TonRevenueSource='deposit'|'battle_pass'|'egg_purchase'|'pet_purchase'|'premium_shop'|'event_purchase'|'other';
/** Accounting split of confirmed TON revenue: the player keeps the full product, the pool books its share. */
export function poolContributionTon(amountTon:number,percent:number=COMMUNITY_POOL_PERCENT){if(!Number.isFinite(amountTon)||amountTon<=0)return 0;const pct=Math.min(100,Math.max(0,percent));return Math.round(amountTon*pct/100*1e9)/1e9}
export const POOL_MINIMUM_POINTS=500,POOL_MINIMUM_HEROES=5;
/** Single source of truth mirrored by the backend `pool_eligibility(uuid)`: 500+ points AND 5+ owned heroes. */
export function poolEligibility(points:number,ownedHeroes:number,banned=false,minimumPoints=POOL_MINIMUM_POINTS,minimumHeroes=POOL_MINIMUM_HEROES){return!banned&&points>=minimumPoints&&ownedHeroes>=minimumHeroes}
/** Normalises the dashboard payload into the requirement breakdown shown in the UI. */
export function resolvePoolEligibility(data:CommunityPoolDashboard):PoolEligibility{const minimumPoints=data.eligibility?.minimumPoints??data.settings.minimumPoints??POOL_MINIMUM_POINTS,minimumHeroes=data.eligibility?.minimumHeroes??data.settings.minimumHeroes??POOL_MINIMUM_HEROES,points=data.eligibility?.points??data.player.points??0,ownedHeroes=data.eligibility?.ownedHeroes??data.player.ownedHeroes??0,banned=data.eligibility?.banned??false;return{points,minimumPoints,ownedHeroes,minimumHeroes,pointsEligible:points>=minimumPoints,heroesEligible:ownedHeroes>=minimumHeroes,banned,eligible:poolEligibility(points,ownedHeroes,banned,minimumPoints,minimumHeroes)}}
export function secureWeightedIndex(weights:number[],unit:number){const total=weights.reduce((sum,value)=>sum+Math.max(0,value),0);if(total<=0)return-1;let cursor=Math.min(.999999999999,Math.max(0,unit))*total;for(let i=0;i<weights.length;i++){cursor-=Math.max(0,weights[i]);if(cursor<0)return i}return weights.length-1}
export function buildCommunityPoolPreview():CommunityPoolDashboard{const now=Date.now(),ends=now+2*86400000+14*3600000+32*60000;return{season:{id:'preview-pool-week',weekLabel:'Semana 32',balanceTon:12.435,startsAt:new Date(now-4*86400000).toISOString(),endsAt:new Date(ends).toISOString(),status:'active'},player:{points:1280,position:18,eligible:true,walletConnected:true,accountAgeDays:34,hasHero:true,ownedHeroes:7,pointsEligible:true,heroesEligible:true},eligibility:{points:1280,minimumPoints:500,ownedHeroes:7,minimumHeroes:5,pointsEligible:true,heroesEligible:true,eligible:true},settings:{minimumPoints:500,minimumHeroes:5,rankingSharePercent:70,lotterySharePercent:30},participantCount:1847,ranking:[{position:1,playerId:'p1',name:'Rei da Forja',avatarUrl:null,points:18420,eligible:true,estimatedPrizeTon:1.3057},{position:2,playerId:'p2',name:'Valquíria',avatarUrl:null,points:15280,eligible:true,estimatedPrizeTon:.8705},{position:3,playerId:'p3',name:'Mestre Anão',avatarUrl:null,points:13640,eligible:true,estimatedPrizeTon:.6964},{position:4,playerId:'p4',name:'Arqueira Lunar',avatarUrl:null,points:11800,eligible:true,estimatedPrizeTon:.0373},{position:5,playerId:'p5',name:'Guardião Rubro',avatarUrl:null,points:10950,eligible:true,estimatedPrizeTon:.0373}],history:[{id:'h1',weekLabel:'Semana 31',amountTon:10.82,winnerCount:106,playerRewardTon:.042,distributedAt:new Date(now-5*86400000).toISOString()},{id:'h2',weekLabel:'Semana 30',amountTon:9.64,winnerCount:103,playerRewardTon:0,distributedAt:new Date(now-12*86400000).toISOString()}]}}
