export type LanguageCode = 'pt' | 'en' | 'es' | 'ru';
export type Translator = (key: string) => string;

const en: Record<string, string> = {
  blacksmith: 'Village blacksmith', level: 'Level', calendar: 'Calendar', collectedToday: 'Collected today', day: 'Day', open: 'Open',
  notifications: 'Notifications', rewardCollected: 'Daily reward collected.', rewardAvailable: 'Your daily reward is available!', settings: 'Settings', language: 'Language',
  dailyRewards: 'Daily rewards', calendar30: '30-day calendar', selectDay: 'Select the highlighted day to receive your FC reward.',
  returning: 'Returning shortly...', kills: 'Defeats', damageDealt: 'Damage dealt', killReward: 'Defeat reward', combatTeam: 'Combat team', autoDamage: 'AUTO DAMAGE', heroLevel: 'Lv. 1', heroesAttack: 'The 5 heroes attack together every 10 seconds',
  inProgress: 'In progress', processing: 'Processing...', common: 'Common', uncommon: 'Uncommon', rare: 'Rare', epic: 'Epic', legendary: 'Legendary',
  buildingLocked: 'This building is still locked.', bossDefeated: 'Boss defeated!', bossReturned: 'The Ancient Dragon has returned!', walletDisconnected: 'Wallet disconnected', walletError: 'Unable to disconnect wallet',
  shop: 'Hero Shop', recruit: 'Recruit', recruitment: 'Hero recruitment', odds: 'Summon odds', latestHeroes: 'Latest heroes', owned: 'Owned', close: 'Close', notEnoughFc: 'Not enough FC for this recruitment.',
  bossTotalDamage: 'Total damage', bossReward: 'Reward', teamAttack: 'Team ATK', teamHealth: 'Team HP', damagePerCycle: 'Damage / 10s', timeRemainingLabel: 'Time remaining', waitingRevive: 'Waiting for heroes to revive', rarityEstimate: 'Rarity estimate', nextAttacks: 'Next attacks', teamLabel: 'Team', bossLabel: 'Boss', combatEquipment: 'Combat equipment', officialBackend: 'OFFICIAL BACKEND', syncingBackend: 'SYNCING...', defeated: 'Defeated', revivesIn: 'Revives in', selectHero: 'Select hero', slot: 'Slot', collectReward: 'COLLECT', levelShort: 'Lv.',
  heroEquipped: 'Hero equipped!', equipFailed: 'Unable to equip the hero.', backendRequired: 'The combat backend is required.', equippedInSlot: 'Equipped in Slot', noSlotSelected: 'No slot selected.', invalidHero: 'Invalid hero.', testMode: 'TEST MODE',
  pool: 'Pool', pvp: 'PvP', invite: 'Invite', comingSoon: 'Coming soon',
  referralTitle:'Invitations',myLink:'My link',copyLink:'Copy link',shareTelegram:'Share',openQr:'QR Code',qrError:'Unable to create QR Code.',linkCopied:'Link copied!',inviteShareText:'Join me in Forge Village!',totalInvites:'Total',totalCommissions:'FC earned',today:'Today',yesterday:'Yesterday',total:'Total',referralTree:'Referral tree',you:'You',invitedList:'Invites',history:'History',ranking:'Ranking',online:'Online',lastSeen:'Last seen',generated:'Generated',noInvites:'No invitations yet.',noCommissions:'No commissions yet.',player:'Player',invites:'invites',milestones:'Milestones',disabled:'Disabled',scanQr:'Scan to join',referralLoadError:'Unable to load invitations.',
  'building.iron-mine': 'Iron Mine', 'building.coal-mine': 'Coal Mine', 'building.forge': 'Forge', 'building.royal-workshop': 'Royal Workshop', 'building.dragon-foundry': 'Dragon Foundry',
  'mission.mission-1.title': 'Open the game', 'mission.mission-1.desc': 'Visit Forge Village and keep your streak alive.',
  'mission.mission-2.title': 'Collect production', 'mission.mission-2.desc': 'Collect your accumulated Forge Coins.',
  'mission.mission-3.title': 'Upgrade a building', 'mission.mission-3.desc': 'Improve one of your village buildings.',
  'mission.mission-4.title': 'Fight the boss', 'mission.mission-4.desc': 'Send your heroes against the Ancient Dragon.',
  'mission.mission-5.title': 'Invite a friend', 'mission.mission-5.desc': 'Share Forge Village with a friend.'
};

const pt: Record<string, string> = {
  blacksmith: 'Ferreiro da vila', level: 'Nível', calendar: 'Calendário', collectedToday: 'Coletado hoje', day: 'Dia', open: 'Abrir',
  notifications: 'Notificações', rewardCollected: 'Recompensa diária coletada.', rewardAvailable: 'Sua recompensa diária está disponível!', settings: 'Configurações', language: 'Idioma',
  dailyRewards: 'Recompensas diárias', calendar30: 'Calendário de 30 dias', selectDay: 'Selecione o dia destacado para receber a recompensa em FC.',
  returning: 'Retornando em instantes...', kills: 'Abates', damageDealt: 'Dano causado', killReward: 'Recompensa por abate', combatTeam: 'Equipe de combate', autoDamage: 'DANO AUTOMÁTICO', heroLevel: 'Nv. 1', heroesAttack: 'Os 5 heróis atacam juntos a cada 10 segundos',
  inProgress: 'Em andamento', processing: 'Processando...', common: 'Comum', uncommon: 'Incomum', rare: 'Raro', epic: 'Épico', legendary: 'Lendário',
  buildingLocked: 'Esta construção ainda está bloqueada.', bossDefeated: 'Chefe derrotado!', bossReturned: 'O Dragão Ancestral retornou!', walletDisconnected: 'Carteira desconectada', walletError: 'Não foi possível desconectar a carteira',
  shop: 'Loja de Heróis', recruit: 'Recrutar', recruitment: 'Recrutamento de heróis', odds: 'Chances de invocação', latestHeroes: 'Últimos heróis', owned: 'Possui', close: 'Fechar', notEnoughFc: 'FC insuficiente para este recrutamento.',
  bossTotalDamage: 'Dano total', bossReward: 'Recompensa', teamAttack: 'ATK da equipe', teamHealth: 'HP da equipe', damagePerCycle: 'Dano / 10s', timeRemainingLabel: 'Tempo restante', waitingRevive: 'Aguardando heróis reviverem', rarityEstimate: 'Estimativa por raridade', nextAttacks: 'Próximos ataques', teamLabel: 'Equipe', bossLabel: 'Chefe', combatEquipment: 'Equipamento de combate', officialBackend: 'BACKEND OFICIAL', syncingBackend: 'SINCRONIZANDO...', defeated: 'Derrotado', revivesIn: 'Revive em', selectHero: 'Selecionar herói', slot: 'Slot', collectReward: 'COLETAR', levelShort: 'Nv.',
  heroEquipped: 'Herói equipado!', equipFailed: 'Não foi possível equipar o herói.', backendRequired: 'O backend de combate é necessário.', equippedInSlot: 'Equipado no Slot', noSlotSelected: 'Nenhum slot selecionado.', invalidHero: 'Herói inválido.', testMode: 'MODO DE TESTE',
  pool: 'Pool', pvp: 'PvP', invite: 'Convite', comingSoon: 'Em breve',
  referralTitle:'Convites',myLink:'Meu link',copyLink:'Copiar link',shareTelegram:'Compartilhar',openQr:'QR Code',qrError:'Não foi possível criar o QR Code.',linkCopied:'Link copiado!',inviteShareText:'Junte-se a mim no Forge Village!',totalInvites:'Total',totalCommissions:'FC ganhos',today:'Hoje',yesterday:'Ontem',total:'Total',referralTree:'Árvore de convites',you:'Você',invitedList:'Convidados',history:'Histórico',ranking:'Ranking',online:'Online',lastSeen:'Último acesso',generated:'Gerou',noInvites:'Nenhum convidado ainda.',noCommissions:'Nenhuma comissão ainda.',player:'Jogador',invites:'convites',milestones:'Metas de convidados',disabled:'Desativado',scanQr:'Escaneie para entrar',referralLoadError:'Não foi possível carregar os convites.',
  'building.iron-mine': 'Mina de Ferro', 'building.coal-mine': 'Mina de Carvão', 'building.forge': 'Forja', 'building.royal-workshop': 'Oficina Real', 'building.dragon-foundry': 'Fundição do Dragão',
  'mission.mission-1.title': 'Abrir o jogo', 'mission.mission-1.desc': 'Visite Forge Village e mantenha sua sequência.',
  'mission.mission-2.title': 'Coletar produção', 'mission.mission-2.desc': 'Colete suas Forge Coins acumuladas.',
  'mission.mission-3.title': 'Melhorar construção', 'mission.mission-3.desc': 'Melhore uma construção da sua vila.',
  'mission.mission-4.title': 'Enfrentar o chefe', 'mission.mission-4.desc': 'Envie seus heróis contra o Dragão Ancestral.',
  'mission.mission-5.title': 'Convidar um amigo', 'mission.mission-5.desc': 'Compartilhe Forge Village com um amigo.'
};

const es: Record<string, string> = {
  ...en, blacksmith: 'Herrero de la aldea', level: 'Nivel', calendar: 'Calendario', collectedToday: 'Recogido hoy', day: 'Día', open: 'Abrir', notifications: 'Notificaciones', rewardCollected: 'Recompensa diaria recogida.', rewardAvailable: '¡Tu recompensa diaria está disponible!', settings: 'Configuración', language: 'Idioma', dailyRewards: 'Recompensas diarias', calendar30: 'Calendario de 30 días', selectDay: 'Selecciona el día destacado para recibir FC.', returning: 'Regresando pronto...', kills: 'Derrotas', damageDealt: 'Daño causado', killReward: 'Recompensa por derrota', combatTeam: 'Equipo de combate', autoDamage: 'DAÑO AUTOMÁTICO', heroLevel: 'Nv. 1', heroesAttack: 'Los 5 héroes atacan juntos cada 10 segundos', inProgress: 'En progreso', processing: 'Procesando...', common: 'Común', uncommon: 'Poco común', rare: 'Raro', epic: 'Épico', legendary: 'Legendario', buildingLocked: 'Este edificio aún está bloqueado.', bossDefeated: '¡Jefe derrotado!', bossReturned: '¡El Dragón Ancestral ha regresado!', walletDisconnected: 'Billetera desconectada', walletError: 'No se pudo desconectar la billetera',
  'building.iron-mine': 'Mina de Hierro', 'building.coal-mine': 'Mina de Carbón', 'building.forge': 'Forja', 'building.royal-workshop': 'Taller Real', 'building.dragon-foundry': 'Fundición del Dragón',
  bossTotalDamage: 'Daño total', bossReward: 'Recompensa', teamAttack: 'ATQ del equipo', teamHealth: 'PV del equipo', damagePerCycle: 'Daño / 10s', timeRemainingLabel: 'Tiempo restante', waitingRevive: 'Esperando que revivan los héroes', rarityEstimate: 'Estimación por rareza', nextAttacks: 'Próximos ataques', teamLabel: 'Equipo', bossLabel: 'Jefe', combatEquipment: 'Equipo de combate', officialBackend: 'SERVIDOR OFICIAL', syncingBackend: 'SINCRONIZANDO...', defeated: 'Derrotado', revivesIn: 'Revive en', selectHero: 'Seleccionar héroe', slot: 'Espacio', collectReward: 'RECOGER', levelShort: 'Nv.'
  ,heroEquipped: '¡Héroe equipado!', equipFailed: 'No se pudo equipar al héroe.', backendRequired: 'Se necesita el servidor de combate.', equippedInSlot: 'Equipado en el espacio', noSlotSelected: 'Ningún espacio seleccionado.', invalidHero: 'Héroe inválido.', testMode: 'MODO DE PRUEBA', pool: 'Pool', pvp: 'PvP', invite: 'Invitar', comingSoon: 'Próximamente',referralTitle:'Invitaciones',myLink:'Mi enlace',copyLink:'Copiar enlace',shareTelegram:'Compartir',openQr:'Código QR',qrError:'No se pudo crear el código QR.',linkCopied:'¡Enlace copiado!',inviteShareText:'¡Únete a mí en Forge Village!',totalInvites:'Total',totalCommissions:'FC ganados',today:'Hoy',yesterday:'Ayer',total:'Total',referralTree:'Árbol de invitaciones',you:'Tú',invitedList:'Invitados',history:'Historial',ranking:'Clasificación',online:'En línea',lastSeen:'Último acceso',generated:'Generó',noInvites:'Aún no hay invitados.',noCommissions:'Aún no hay comisiones.',player:'Jugador',invites:'invitaciones',milestones:'Metas',disabled:'Desactivado',scanQr:'Escanea para entrar',referralLoadError:'No se pudieron cargar las invitaciones.'
};

const ru: Record<string, string> = {
  ...en, blacksmith: 'Кузнец деревни', level: 'Уровень', calendar: 'Календарь', collectedToday: 'Получено сегодня', day: 'День', open: 'Открыть', notifications: 'Уведомления', rewardCollected: 'Ежедневная награда получена.', rewardAvailable: 'Ежедневная награда доступна!', settings: 'Настройки', language: 'Язык', dailyRewards: 'Ежедневные награды', calendar30: 'Календарь на 30 дней', selectDay: 'Выберите выделенный день, чтобы получить FC.', returning: 'Скоро вернется...', kills: 'Победы', damageDealt: 'Нанесенный урон', killReward: 'Награда за победу', combatTeam: 'Боевая команда', autoDamage: 'АВТОУРОН', heroLevel: 'Ур. 1', heroesAttack: '5 героев атакуют вместе каждые 10 секунд', inProgress: 'В процессе', processing: 'Обработка...', common: 'Обычный', uncommon: 'Необычный', rare: 'Редкий', epic: 'Эпический', legendary: 'Легендарный', buildingLocked: 'Это здание еще заблокировано.', bossDefeated: 'Босс побежден!', bossReturned: 'Древний Дракон вернулся!', walletDisconnected: 'Кошелек отключен', walletError: 'Не удалось отключить кошелек',
  'building.iron-mine': 'Железная шахта', 'building.coal-mine': 'Угольная шахта', 'building.forge': 'Кузница', 'building.royal-workshop': 'Королевская мастерская', 'building.dragon-foundry': 'Драконья литейная',
  bossTotalDamage: 'Общий урон', bossReward: 'Награда', teamAttack: 'АТК команды', teamHealth: 'HP команды', damagePerCycle: 'Урон / 10с', timeRemainingLabel: 'Осталось времени', waitingRevive: 'Ожидание возрождения героев', rarityEstimate: 'Оценка по редкости', nextAttacks: 'Следующие атаки', teamLabel: 'Команда', bossLabel: 'Босс', combatEquipment: 'Боевой отряд', officialBackend: 'ОФИЦИАЛЬНЫЙ СЕРВЕР', syncingBackend: 'СИНХРОНИЗАЦИЯ...', defeated: 'Побеждён', revivesIn: 'Возродится через', selectHero: 'Выбрать героя', slot: 'Слот', collectReward: 'ПОЛУЧИТЬ', levelShort: 'Ур.'
  ,heroEquipped: 'Герой экипирован!', equipFailed: 'Не удалось экипировать героя.', backendRequired: 'Требуется боевой сервер.', equippedInSlot: 'Экипирован в слот', noSlotSelected: 'Слот не выбран.', invalidHero: 'Недопустимый герой.', testMode: 'ТЕСТОВЫЙ РЕЖИМ', pool: 'Пул', pvp: 'PvP', invite: 'Пригласить', comingSoon: 'Скоро',referralTitle:'Приглашения',myLink:'Моя ссылка',copyLink:'Копировать',shareTelegram:'Поделиться',openQr:'QR-код',qrError:'Не удалось создать QR-код.',linkCopied:'Ссылка скопирована!',inviteShareText:'Присоединяйтесь ко мне в Forge Village!',totalInvites:'Всего',totalCommissions:'Заработано FC',today:'Сегодня',yesterday:'Вчера',total:'Всего',referralTree:'Дерево приглашений',you:'Вы',invitedList:'Приглашённые',history:'История',ranking:'Рейтинг',online:'Онлайн',lastSeen:'Последний вход',generated:'Создано',noInvites:'Приглашений пока нет.',noCommissions:'Комиссий пока нет.',player:'Игрок',invites:'приглашений',milestones:'Цели',disabled:'Отключено',scanQr:'Сканируйте для входа',referralLoadError:'Не удалось загрузить приглашения.'
};

export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = { pt, en, es, ru };
export const translate = (language: LanguageCode, key: string) => UI_TRANSLATIONS[language][key] ?? en[key] ?? key;
