import type{HeroRarity}from'./combat';import type{HeroArchetype}from'./pvpRules';
export type PvpHero={heroId:string;name:string;imageUrl:string;rarity:HeroRarity;level:number;archetype:HeroArchetype;finalAtk:number;finalHp:number;defense:number;speed:number;power:number;slot?:number};
export type PvpHistory={id:string;opponentName:string;result:'win'|'loss';turns:number;trophyChange:number;rewardFc:number;createdAt:string};
export type PvpRank={position:number;id:string;name:string;avatarUrl:string|null;trophies:number;league:string;wins:number};
export type PvpDashboard={userId:string;trophies:number;league:string;tickets:number;wins:number;losses:number;attackTeam:PvpHero[];defenseTeam:PvpHero[];teamPower:number;ownedHeroes:PvpHero[];history:PvpHistory[];ranking:PvpRank[]};
export type PvpOpponent={userId:string;name:string;avatarUrl:string|null;trophies:number;league:string;teamPower:number;wins:number;defenseTeam:PvpHero[]};
export type PvpBattleResult={battleId:string;result:'attacker_win'|'defender_win';winnerId:string;totalTurns:number;rewardFc:number;trophyChange:number;battleLog:Array<{turn:number;side:string;attackerId:string;targetId:string;damage:number;remainingHp:number}>;attackerState:PvpHero[];defenderState:PvpHero[]};

const previewHero=(heroId:string,name:string,imageUrl:string,rarity:HeroRarity,level:number,archetype:HeroArchetype,finalAtk:number,finalHp:number,slot?:number):PvpHero=>({heroId,name,imageUrl,rarity,level,archetype,finalAtk,finalHp,defense:Math.round(finalHp*.09),speed:90+level,power:Math.round(finalAtk*2.2+finalHp*.18+level*25),slot});
export function buildPvpDashboardPreview():PvpDashboard{
  const heroes=[previewHero('preview-hero-1','Kael, o Guardião','/assets/game/heroes/legendary-dragon-knight.png','legendary',18,'warrior',612,4820,1),previewHero('preview-hero-2','Lyra da Lua','/assets/game/heroes/shop/epic-2.webp','epic',15,'mage',478,3140,2),previewHero('preview-hero-3','Brom Punho de Ferro','/assets/game/heroes/rare-guardian.png','rare',14,'tank',342,4260,3),previewHero('preview-hero-4','Arwen Sombria','/assets/game/heroes/uncommon-archer.png','uncommon',12,'archer',286,2480,4),previewHero('preview-hero-5','Darian da Forja','/assets/game/heroes/common-warrior.png','common',10,'assassin',238,2010,5),previewHero('preview-hero-6','Selene Arcana','/assets/game/heroes/shop/epic-3.webp','epic',11,'support',376,2920)];
  return{userId:'preview-player',trophies:1460,league:'Liga Ouro',tickets:5,wins:28,losses:11,attackTeam:heroes.slice(0,5),defenseTeam:heroes.slice(0,5),teamPower:heroes.slice(0,5).reduce((sum,hero)=>sum+hero.power,0),ownedHeroes:heroes,history:[{id:'preview-battle-1',opponentName:'Lord Valerian',result:'win',turns:14,trophyChange:22,rewardFc:3200,createdAt:new Date(Date.now()-7200000).toISOString()},{id:'preview-battle-2',opponentName:'Morgana',result:'loss',turns:19,trophyChange:-12,rewardFc:0,createdAt:new Date(Date.now()-93600000).toISOString()}],ranking:[{position:1,id:'rank-1',name:'Rei da Forja',avatarUrl:null,trophies:2840,league:'Liga Lendária',wins:94},{position:2,id:'rank-2',name:'Valquíria',avatarUrl:null,trophies:2660,league:'Liga Lendária',wins:87},{position:3,id:'preview-player',name:'Senhor Arwen',avatarUrl:null,trophies:1460,league:'Liga Ouro',wins:28}]};
}
export function buildPvpOpponentPreview():PvpOpponent[]{const base=buildPvpDashboardPreview();return[{userId:'preview-opponent-1',name:'Lord Valerian',avatarUrl:null,trophies:1512,league:'Liga Ouro',teamPower:base.teamPower+420,wins:31,defenseTeam:base.defenseTeam},{userId:'preview-opponent-2',name:'Morgana da Névoa',avatarUrl:null,trophies:1398,league:'Liga Ouro',teamPower:base.teamPower-310,wins:24,defenseTeam:[...base.defenseTeam].reverse()}]}
