import{normalizeRarity,type HeroRarity}from'./combat';
export type HeroArchetype='warrior'|'assassin'|'tank'|'mage'|'archer'|'support';
export const HERO_ARCHETYPE_MULTIPLIERS:Record<HeroArchetype,{atk:number;hp:number}>={warrior:{atk:1,hp:1.15},assassin:{atk:1.15,hp:.9},tank:{atk:.85,hp:1.3},mage:{atk:1.2,hp:.85},archer:{atk:1.1,hp:1},support:{atk:.9,hp:1.1}};
/** Rarity bands never overlap: any hero of a higher rarity outranks every hero of a lower one. */
export const PVP_RARITY_STATS:Record<HeroRarity,{minAtk:number;maxAtk:number;minHp:number;maxHp:number;minAtkGrowth:number;maxAtkGrowth:number;minHpGrowth:number;maxHpGrowth:number}>={common:{minAtk:100,maxAtk:170,minHp:1000,maxHp:1700,minAtkGrowth:.025,maxAtkGrowth:.03,minHpGrowth:.04,maxHpGrowth:.045},uncommon:{minAtk:180,maxAtk:260,minHp:1800,maxHp:2600,minAtkGrowth:.028,maxAtkGrowth:.033,minHpGrowth:.042,maxHpGrowth:.048},rare:{minAtk:270,maxAtk:380,minHp:2700,maxHp:3800,minAtkGrowth:.031,maxAtkGrowth:.036,minHpGrowth:.045,maxHpGrowth:.051},epic:{minAtk:390,maxAtk:520,minHp:3900,maxHp:5200,minAtkGrowth:.034,maxAtkGrowth:.039,minHpGrowth:.048,maxHpGrowth:.054},legendary:{minAtk:530,maxAtk:700,minHp:5300,maxHp:7000,minAtkGrowth:.037,maxAtkGrowth:.042,minHpGrowth:.051,maxHpGrowth:.057},mythic:{minAtk:720,maxAtk:950,minHp:7200,maxHp:9500,minAtkGrowth:.04,maxAtkGrowth:.045,minHpGrowth:.054,maxHpGrowth:.06},ancestral:{minAtk:980,maxAtk:1300,minHp:9800,maxHp:13000,minAtkGrowth:.043,maxAtkGrowth:.048,minHpGrowth:.057,maxHpGrowth:.063},nft_exclusive:{minAtk:1350,maxAtk:1800,minHp:13500,maxHp:18000,minAtkGrowth:.04515,maxAtkGrowth:.0504,minHpGrowth:.05985,maxHpGrowth:.06615},celestial:{minAtk:15000,maxAtk:16500,minHp:15000,maxHp:16500,minAtkGrowth:.05,maxAtkGrowth:.055,minHpGrowth:.066,maxHpGrowth:.072}};
export const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,Number.isFinite(v)?v:min));
export function hashSeed(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
export function seededUnit(seed:string){return hashSeed(seed)/4294967295}
export function seededRange(seed:string,min:number,max:number){return Math.round(min+seededUnit(seed)*(max-min))}
export function seededDecimal(seed:string,min:number,max:number){return min+seededUnit(seed)*(max-min)}
export type GeneratedHeroStats={baseAtk:number;baseHp:number;attackGrowth:number;hpGrowth:number;archetype:HeroArchetype;statsSeed:string};
export function generateHeroStats(id:string,template:string,userId:string,createdAt:string,rarityValue:string,archetype?:HeroArchetype):GeneratedHeroStats{const rarity=normalizeRarity(rarityValue),range=PVP_RARITY_STATS[rarity],seed=`${id}:${template}:${userId}:${createdAt}`,types=Object.keys(HERO_ARCHETYPE_MULTIPLIERS)as HeroArchetype[],kind=archetype??types[hashSeed(seed)%types.length],mult=HERO_ARCHETYPE_MULTIPLIERS[kind];return{baseAtk:clamp(Math.round(seededRange(`${seed}:atk`,range.minAtk,range.maxAtk)*mult.atk),range.minAtk,range.maxAtk),baseHp:clamp(Math.round(seededRange(`${seed}:hp`,range.minHp,range.maxHp)*mult.hp),range.minHp,range.maxHp),attackGrowth:Number(seededDecimal(`${seed}:ag`,range.minAtkGrowth,range.maxAtkGrowth).toFixed(5)),hpGrowth:Number(seededDecimal(`${seed}:hg`,range.minHpGrowth,range.maxHpGrowth).toFixed(5)),archetype:kind,statsSeed:seed}}
export function finalHeroStats(baseAtk:number,baseHp:number,attackGrowth:number,hpGrowth:number,level:number,bonusAtk=0,bonusHp=0){const lv=Math.max(1,Math.floor(Number.isFinite(level)?level:1)),atk=(Number.isFinite(baseAtk)?baseAtk:1)+(Number.isFinite(bonusAtk)?bonusAtk:0),hp=(Number.isFinite(baseHp)?baseHp:1)+(Number.isFinite(bonusHp)?bonusHp:0);return{finalAtk:Math.max(1,Math.round(Math.max(1,atk)*Math.pow(1+clamp(attackGrowth,0,.2),lv-1))),finalHp:Math.max(1,Math.round(Math.max(1,hp)*Math.pow(1+clamp(hpGrowth,0,.2),lv-1)))}}
export function heroPower(finalAtk:number,finalHp:number,level:number,defense=0,speed=0){return Math.max(1,Math.round(clamp(finalAtk,1,1e9)*2.2+clamp(finalHp,1,1e10)*.18+Math.max(1,level)*25+Math.max(0,defense)*.5+Math.max(0,speed)*2))}
export type PvpFighter={heroId:string;name:string;finalAtk:number;finalHp:number;level:number;speed?:number;defense?:number};
export function teamSummary(team:PvpFighter[]){return team.reduce((s,h)=>({atk:s.atk+h.finalAtk,hp:s.hp+h.finalHp,power:s.power+heroPower(h.finalAtk,h.finalHp,h.level,h.defense,h.speed)}),{atk:0,hp:0,power:0})}
export function deterministicDamage(attacker:PvpFighter,defender:PvpFighter,battleSeed:string,turn:number){const reduction=Math.max(0,defender.defense??0)/(Math.max(0,defender.defense??0)+300),variance=.95+seededUnit(`${battleSeed}:${turn}:damage`)*.1;return Math.max(1,Math.round(attacker.finalAtk*(1-reduction)*variance))}
export function uniqueTeam(ids:string[]){return ids.length<=5&&ids.every(Boolean)&&new Set(ids).size===ids.length}
export function matchmakingWindow(power:number,trophies:number,candidates:Array<{id:string;power:number;trophies:number;hasDefense:boolean;banned?:boolean}>,selfId:string,seen:string[]=[]){const windows=[[.2,150],[.35,300],[.5,500]]as const;for(const[p,t]of windows){const found=candidates.filter(x=>x.id!==selfId&&x.hasDefense&&!x.banned&&Math.abs(x.power-power)<=Math.max(1,power*p)&&Math.abs(x.trophies-trophies)<=t).sort((a,b)=>(seen.includes(a.id)?1:0)-(seen.includes(b.id)?1:0)||Math.abs(a.power-power)-Math.abs(b.power-power)).slice(0,3);if(found.length)return found}return[]}
