export type SeasonPassTier='none'|'adventurer'|'legendary';export type SeasonRewardTier=Exclude<SeasonPassTier,'none'>;export type PassTier=SeasonRewardTier;export type PassReward={id:string;level:number;tier:SeasonRewardTier;type:string;code:string|null;amount:number;title:string;claimed:boolean;unlocked:boolean;requiresPassVersion?:number;versionLocked?:boolean;/** Locked reward that can be unlocked by paying the fixed TON price (server-owned). */purchasable?:boolean;priceTon?:number|null};
export type PassXpGain={id:string;source:string;baseXp:number;multiplier:number;xp:number;levelUp:boolean;level:number;createdAt:string};
export type SeasonPassDashboard={season:{id:string;name:string;endsAt:string;levels:number;xpPerLevel:number;adventurerPriceTon:number;legendaryPriceTon:number;upgradePriceTon:number;passVersion?:number;currentPassVersion?:number};player:{xp:number;level:number;tier:SeasonPassTier;adventurerOwned:boolean;legendaryOwned:boolean;totalXp?:number;maxXp?:number;maxed?:boolean;xpIntoLevel?:number;xpForNextLevel?:number;xpMultiplier?:number;xpBonusPercent?:number;passVersion?:number;legacyPass?:boolean;expiresAt?:string|null};rewards:PassReward[];xpRates?:Record<string,number>;xpMultipliers?:Record<string,number>;xpCaps?:Record<string,number>;xpToday?:number;levelPurchase?:PassLevelPurchaseConfig;lockedPurchase?:PassLockedPurchaseConfig;purchase?:{levelsBought:number;fcSpent:number;levelBefore:number;levelAfter:number}};
export type PassLevelPurchaseConfig={enabled:boolean;prices:Record<string,number>;dailyLimit:number;boughtToday:number;remainingToday:number;maxAvailable:number;balanceFc:number};
/** Paid unlock of rewards that require a newer pass: internal TON balance first, TonConnect otherwise. */
export type PassLockedPurchaseConfig={enabled:boolean;priceTon:number;availableTon:number};
export type PassLockedPurchaseResult={status:'completed'|'payment_required'|string;method?:'internal_ton'|'ton_connect';orderId?:string;priceTon?:number;paymentAddress?:string;amountNano?:string;amountTon?:number;paymentComment?:string;expiresAt?:string;availableTon?:number;dashboard?:SeasonPassDashboard};

export type SeasonPassOrder={id:string;paymentAddress:string;amountNano:string;amountTon:number;paymentComment:string;expiresAt:string};
export const SEASON_LEVELS=30;export const PASS_PRICES={adventurer:5,legendary:20,upgrade:15}as const;
export const progressPercent=(xp:number,xpPerLevel:number)=>Math.max(0,Math.min(100,(xp%xpPerLevel)/xpPerLevel*100));
const EQUIP_SLOTS=['weapon','armor','ring'] as const;
const equipTitle:Record<string,string>={weapon:'RARE WEAPON',armor:'RARE ARMOR',ring:'RARE RING'};
export function buildSeasonPassPreview():SeasonPassDashboard{const endsAt=new Date(Date.now()+30*86400000).toISOString(),rewards:PassReward[]=[];for(let level=1;level<=30;level++)for(const tier of ['adventurer','legendary']as SeasonRewardTier[]){const isAdventure=tier==='adventurer',exclusive=level===30;let type=exclusive?(isAdventure?'hero_chest':'skin'):isAdventure?(level%5===0?'equipment':level%3===0?'hero_chest':level%2===0?'pet_food':'fragments'):(level%3===0?'equipment':level%5===0?'pet_egg':level%2===0?'hero_chest':'skin');let code:string|null=exclusive?(isAdventure?'season-1-aldren':'season-1-mythic-egg'):null,amount=1;
 if(level===13&&!exclusive)type='hero_random';
 if(level===26&&tier==='legendary'){type='pvp_ticket';amount=20}
 if(type==='equipment')code=EQUIP_SLOTS[level%EQUIP_SLOTS.length];
 if(type==='hero_random')code='legendary';
 if(type==='pet_egg')code=level===20||level===25?'epic-egg':'rare-egg';
 const title=exclusive?(isAdventure?'HERÓI EXCLUSIVO MISTERIOSO':'PET EXCLUSIVO MISTERIOSO'):type==='equipment'?equipTitle[code??'weapon']:type==='hero_random'?'MYSTERY LEGENDARY HERO':type==='pvp_ticket'?`PVP TICKETS x${amount}`:({hero_chest:isAdventure?'Baú Aprimorado':'Baú Especial',pet_food:'Comida de Pet',fragments:'Fragmentos',pet_egg:code==='epic-egg'?'Ovo Épico':'Ovo Raro',skin:'Fragmento Universal'}as Record<string,string>)[type];
 rewards.push({id:`preview-${tier}-${level}`,level,tier,type,code,amount,title,claimed:false,unlocked:false})}return{season:{id:'preview',name:'Temporada 1',endsAt,levels:30,xpPerLevel:1000,adventurerPriceTon:5,legendaryPriceTon:20,upgradePriceTon:15},player:{xp:0,level:1,tier:'none',adventurerOwned:false,legendaryOwned:false,xpIntoLevel:0,xpForNextLevel:1000,maxed:false},rewards}}
