import type { GameState, LanguageStrings } from './types';

export const LANGUAGES: Record<string, LanguageStrings> = {
  en: {
    loading: 'Loading game data...',
    welcome: 'Welcome back to Forge Village!',
    welcomeBack: 'Welcome back, blacksmith',
    approxTon: 'Approx. {amount}',
    productionPerHour: 'Production / hour',
    villageLevel: 'Village level',
    loginStreak: 'Login streak',
    offlineProduction: 'Offline production',
    collect: 'Collect',
    collected: 'Collected {amount} FC!',
    buildings: 'Buildings',
    villageBuildings: 'Village buildings',
    storage: 'Storage capacity',
    upgradeCost: 'Upgrade cost',
    upgrade: 'Upgrade',
    missions: 'Missions',
    dailyQuests: 'Daily quests',
    boss: 'Boss',
    bossHealth: 'Boss health',
    yourDamage: 'Your damage',
    timeRemaining: 'Time remaining',
    hoursLeft: '23h 12m left',
    notEnoughFunds: 'Not enough Forge Coins',
    wallet: 'Wallet',
    profile: 'Profile',
    connectWallet: 'Connect wallet',
    disconnectWallet: 'Disconnect wallet',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    depositTon: 'Deposit TON',
    withdrawFc: 'Withdraw FC',
    depositHistory: 'Deposit history',
    withdrawHistory: 'Withdrawal history',
    pending: 'Pending',
    confirmed: 'Confirmed',
    rejected: 'Rejected',
    paid: 'Paid',
    noWallet: 'No wallet connected',
    missingBackend: 'Wallet integration coming soon',
    tabs: {
      village: 'Village',
      missions: 'Missions',
      boss: 'Boss',
      wallet: 'Wallet',
      profile: 'Profile'
    },
    levelLabel: 'Level'
  },
  pt: {
    loading: 'Carregando dados do jogo...',
    welcome: 'Bem-vindo de volta a Forge Village!',
    welcomeBack: 'Bem-vindo de volta, ferreiro',
    approxTon: 'Aprox. {amount}',
    productionPerHour: 'Produção / hora',
    villageLevel: 'Nível da vila',
    loginStreak: 'Sequência de login',
    offlineProduction: 'Produção offline',
    collect: 'Coletar',
    collected: 'Coletado {amount} FC!',
    buildings: 'Construções',
    villageBuildings: 'Construções da vila',
    storage: 'Capacidade',
    upgradeCost: 'Custo de melhoria',
    upgrade: 'Melhorar',
    missions: 'Missões',
    dailyQuests: 'Missões diárias',
    boss: 'Chefe',
    bossHealth: 'Vida do chefe',
    yourDamage: 'Seu dano',
    timeRemaining: 'Tempo restante',
    hoursLeft: '23h 12m restantes',
    notEnoughFunds: 'FC insuficientes',
    wallet: 'Carteira',
    profile: 'Perfil',
    connectWallet: 'Conectar carteira',
    disconnectWallet: 'Desconectar carteira',
    deposit: 'Depositar',
    withdraw: 'Sacar',
    depositTon: 'Depositar TON',
    withdrawFc: 'Sacar FC',
    depositHistory: 'Histórico de depósitos',
    withdrawHistory: 'Histórico de saques',
    pending: 'Pendente',
    confirmed: 'Confirmado',
    rejected: 'Rejeitado',
    paid: 'Pago',
    noWallet: 'Nenhuma carteira conectada',
    missingBackend: 'Integração de carteira em breve',
    tabs: {
      village: 'Vila',
      missions: 'Missões',
      boss: 'Chefe',
      wallet: 'Carteira',
      profile: 'Perfil'
    },
    levelLabel: 'Nível'
  },
  es: {
    loading: 'Cargando datos del juego...',
    welcome: '¡Bienvenido de nuevo a Forge Village!',
    welcomeBack: 'Bienvenido de nuevo, herrero',
    approxTon: 'Aprox. {amount}',
    productionPerHour: 'Producción / hora',
    villageLevel: 'Nivel de la aldea',
    loginStreak: 'Racha de inicio',
    offlineProduction: 'Producción offline',
    collect: 'Recolectar',
    collected: '¡Recibido {amount} FC!',
    buildings: 'Construcciones',
    villageBuildings: 'Construcciones de la aldea',
    storage: 'Capacidad',
    upgradeCost: 'Costo de mejora',
    upgrade: 'Mejorar',
    missions: 'Misiones',
    dailyQuests: 'Misiones diarias',
    boss: 'Jefe',
    bossHealth: 'Vida del jefe',
    yourDamage: 'Tu daño',
    timeRemaining: 'Tiempo restante',
    hoursLeft: '23h 12m restantes',
    notEnoughFunds: 'FC insuficientes',
    wallet: 'Billetera',
    profile: 'Perfil',
    connectWallet: 'Conectar billetera',
    disconnectWallet: 'Desconectar billetera',
    deposit: 'Depositar',
    withdraw: 'Retirar',
    depositTon: 'Depositar TON',
    withdrawFc: 'Retirar FC',
    depositHistory: 'Historial de depósitos',
    withdrawHistory: 'Historial de retiros',
    pending: 'Pendiente',
    confirmed: 'Confirmado',
    rejected: 'Rechazado',
    paid: 'Pagado',
    noWallet: 'Sin billetera conectada',
    missingBackend: 'Integración de billetera pronto',
    tabs: {
      village: 'Aldea',
      missions: 'Misiones',
      boss: 'Jefe',
      wallet: 'Billetera',
      profile: 'Perfil'
    },
    levelLabel: 'Nivel'
  },
  ru: {
    loading: 'Загрузка данных игры...',
    welcome: 'С возвращением в Forge Village!',
    welcomeBack: 'С возвращением, кузнец',
    approxTon: 'Примерно {amount}',
    productionPerHour: 'Производство / час',
    villageLevel: 'Уровень деревни',
    loginStreak: 'Серия входов',
    offlineProduction: 'Офлайн производство',
    collect: 'Собрать',
    collected: 'Получено {amount} FC!',
    buildings: 'Постройки',
    villageBuildings: 'Постройки деревни',
    storage: 'Вместимость',
    upgradeCost: 'Стоимость улучшения',
    upgrade: 'Улучшить',
    missions: 'Задания',
    dailyQuests: 'Ежедневные задания',
    boss: 'Босс',
    bossHealth: 'Здоровье босса',
    yourDamage: 'Ваш урон',
    timeRemaining: 'Оставшееся время',
    hoursLeft: '23 ч 12 мин',
    notEnoughFunds: 'Недостаточно FC',
    wallet: 'Кошелек',
    profile: 'Профиль',
    connectWallet: 'Подключить кошелек',
    disconnectWallet: 'Отключить кошелек',
    deposit: 'Депозит',
    withdraw: 'Вывести',
    depositTon: 'Депозит TON',
    withdrawFc: 'Вывести FC',
    depositHistory: 'История депозитов',
    withdrawHistory: 'История выводов',
    pending: 'В ожидании',
    confirmed: 'Подтверждено',
    rejected: 'Отклонено',
    paid: 'Оплачено',
    noWallet: 'Кошелек не подключен',
    missingBackend: 'Интеграция кошелька скоро',
    tabs: {
      village: 'Деревня',
      missions: 'Задания',
      boss: 'Босс',
      wallet: 'Кошелек',
      profile: 'Профиль'
    },
    levelLabel: 'Уровень'
  }
};

export const locales: Record<string, LanguageStrings> = {
  en: LANGUAGES.en,
  pt: LANGUAGES.pt,
  es: LANGUAGES.es,
  ru: LANGUAGES.ru
};

export const TABS = ['village', 'missions', 'boss', 'wallet', 'profile'] as const;

export const getLocale = () => {
  const language = navigator.language.toLowerCase();
  if (language.startsWith('pt')) return 'pt';
  if (language.startsWith('es')) return 'es';
  if (language.startsWith('ru')) return 'ru';
  return 'en';
};

export const formatCurrency = (value: number) => value.toLocaleString('en-US');

export const buildDefaults = (): GameState => ({
  balance: 850000,
  level: 7,
  loginStreak: 0,
  lastLoginDate: undefined,
  dailyCycleDate: undefined,
  offlineProduction: 32000,
  lastCollectedAt: new Date().toISOString(),
  productionRate: 14800,
  settings: {
    conversionRate: 100000,
    minDepositTon: 0.1,
    minWithdrawalFc: 500000,
    withdrawalFeePercent: 5,
    offlineCapHours: 8
  },
  buildings: [
    { id: 'iron-mine', name: 'Iron Mine', level: 5, productionPerHour: 5200, storage: 24000, upgradeCost: 180000, locked: false },
    { id: 'coal-mine', name: 'Coal Mine', level: 4, productionPerHour: 4100, storage: 18000, upgradeCost: 150000, locked: false },
    { id: 'forge', name: 'Forge', level: 3, productionPerHour: 3200, storage: 12000, upgradeCost: 120000, locked: false },
    { id: 'royal-workshop', name: 'Royal Workshop', level: 2, productionPerHour: 2400, storage: 9000, upgradeCost: 95000, locked: false },
    { id: 'dragon-foundry', name: 'Dragon Foundry', level: 1, productionPerHour: 1400, storage: 6000, upgradeCost: 75000, locked: true }
  ],
  missions: [
    { id: 'mission-1', title: 'Open the game', description: 'Visit Forge Village and keep your streak alive.', reward: 12000, complete: true },
    { id: 'mission-2', title: 'Collect production', description: 'Collect your accumulated Forge Coins twice today.', reward: 9000, complete: false },
    { id: 'mission-3', title: 'Upgrade a building', description: 'Invest in your village by upgrading one structure.', reward: 15000, complete: false },
    { id: 'mission-4', title: 'Fight the boss', description: 'Attack Ancient Dragon and earn rewards.', reward: 18000, complete: false },
    { id: 'mission-5', title: 'Invite a friend', description: 'Share the village with a friend.', reward: 22000, complete: false }
  ],
  boss: { name: 'Ancient Dragon', healthPercent: 100, playerDamage: 0, participants: 1, timeRemaining: 'Individual', rewards: 120000, teamProgress: 0, maxHealth: 67500, defeats: 0 },
  ledger: [],
  pendingDeposits: [],
  pendingWithdrawals: [],
  heroInventory: {},
  bossTeam: ['', '', '', '', '']
});
