insert into economy_settings(key,value_numeric)values('fc_per_ton',100000)on conflict(key)do update set value_numeric=100000,updated_at=now();
create table if not exists public.wallet_settings(key text primary key,value_text text,value_numeric numeric,updated_at timestamptz not null default now());
insert into public.wallet_settings(key,value_text)values('ton_hot_wallet',null)on conflict(key)do nothing;
create table if not exists public.wallet_deposits(id uuid primary key default gen_random_uuid(),user_id uuid not null references game_players(id),amount_ton numeric not null check(amount_ton>0),amount_fc numeric not null check(amount_fc>0),from_wallet text,status text not null default'pending'check(status in('pending','confirmed','credited','expired')),tx_hash text unique,payment_comment text not null,idempotency_key text unique not null,created_at timestamptz not null default now(),confirmed_at timestamptz,credited_at timestamptz,expires_at timestamptz not null default now()+interval'15 minutes');
create table if not exists public.wallet_withdrawals(id uuid primary key default gen_random_uuid(),user_id uuid not null references game_players(id),amount_fc numeric not null check(amount_fc>=100000 and mod(amount_fc,100000)=0),amount_ton numeric not null check(amount_ton>0),wallet_address text not null,status text not null default'pending'check(status in('pending','processing','completed','rejected','cancelled')),idempotency_key text unique not null,created_at timestamptz not null default now(),processed_at timestamptz,tx_hash text unique);
create table if not exists public.pet_egg_orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references game_players(id),egg_id uuid not null references pet_eggs(id),price_ton numeric not null check(price_ton>0),amount_nano text not null,payment_address text not null,status text not null default'pending'check(status in('pending','paid','delivered','expired','cancelled')),tx_hash text unique,payment_comment text not null,idempotency_key text unique not null,created_at timestamptz not null default now(),paid_at timestamptz,delivered_at timestamptz,expires_at timestamptz not null default now()+interval'15 minutes');
create index if not exists wallet_deposits_user_idx on public.wallet_deposits(user_id,created_at desc);
create index if not exists wallet_withdrawals_user_idx on public.wallet_withdrawals(user_id,created_at desc);
create index if not exists pet_egg_orders_user_idx on public.pet_egg_orders(user_id,created_at desc);

grant all on public.wallet_settings to service_role;
grant all on public.wallet_deposits to service_role;
grant all on public.wallet_withdrawals to service_role;
grant all on public.pet_egg_orders to service_role;
revoke all on public.wallet_settings,public.wallet_deposits,public.wallet_withdrawals,public.pet_egg_orders from anon,authenticated;
alter table public.wallet_settings enable row level security;
alter table public.wallet_deposits enable row level security;
alter table public.wallet_withdrawals enable row level security;
alter table public.pet_egg_orders enable row level security;

create or replace function public.wallet_hot_address()returns text language plpgsql security definer set search_path=public as $$declare a text;begin select value_text into a from wallet_settings where key='ton_hot_wallet';if nullif(trim(a),'')is null then raise exception'HOT_WALLET_NOT_CONFIGURED';end if;return a;end$$;

create or replace function public.create_wallet_deposit(p_telegram_id bigint,p_amount_ton numeric,p_from_wallet text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;rate numeric;d wallet_deposits%rowtype;address text;begin if p_amount_ton<=0 or p_amount_ton>100000 then raise exception'INVALID_DEPOSIT_AMOUNT';end if;select id into u from game_players where telegram_id=p_telegram_id;if u is null then raise exception'PLAYER_NOT_FOUND';end if;select*into d from wallet_deposits where idempotency_key=p_idempotency_key;if d.id is not null then return jsonb_build_object('id',d.id,'paymentAddress',wallet_hot_address(),'amountNano',round(d.amount_ton*1000000000)::text,'amountTon',d.amount_ton,'amountFc',d.amount_fc,'paymentComment',d.payment_comment,'expiresAt',d.expires_at);end if;select value_numeric into rate from economy_settings where key='fc_per_ton';address:=wallet_hot_address();insert into wallet_deposits(user_id,amount_ton,amount_fc,from_wallet,payment_comment,idempotency_key)values(u,p_amount_ton,round(p_amount_ton*rate),p_from_wallet,'forge_deposit:'||gen_random_uuid(),p_idempotency_key)returning*into d;return jsonb_build_object('id',d.id,'paymentAddress',address,'amountNano',round(d.amount_ton*1000000000)::text,'amountTon',d.amount_ton,'amountFc',d.amount_fc,'paymentComment',d.payment_comment,'expiresAt',d.expires_at);end$$;

create or replace function public.request_wallet_withdrawal(p_telegram_id bigint,p_amount_fc numeric,p_wallet_address text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare u game_players%rowtype;rate numeric;w wallet_withdrawals%rowtype;begin if p_amount_fc<100000 then raise exception'WITHDRAWAL_MINIMUM_100000';end if;if mod(p_amount_fc,100000)<>0 then raise exception'WITHDRAWAL_MULTIPLE_100000';end if;if nullif(trim(p_wallet_address),'')is null then raise exception'WALLET_REQUIRED';end if;select*into w from wallet_withdrawals where idempotency_key=p_idempotency_key;if w.id is not null then return jsonb_build_object('id',w.id,'status',w.status,'amountFc',w.amount_fc,'amountTon',w.amount_ton);end if;select*into u from game_players where telegram_id=p_telegram_id for update;if u.id is null then raise exception'PLAYER_NOT_FOUND';end if;if u.forge_coins<p_amount_fc then raise exception'INSUFFICIENT_FC_BALANCE';end if;select value_numeric into rate from economy_settings where key='fc_per_ton';update game_players set forge_coins=forge_coins-p_amount_fc,updated_at=now()where id=u.id;insert into wallet_withdrawals(user_id,amount_fc,amount_ton,wallet_address,idempotency_key)values(u.id,p_amount_fc,p_amount_fc/rate,p_wallet_address,p_idempotency_key)returning*into w;return jsonb_build_object('id',w.id,'status',w.status,'amountFc',w.amount_fc,'amountTon',w.amount_ton);end$$;

create or replace function public.create_pet_egg_order(p_telegram_id bigint,p_egg_id uuid,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;e pet_eggs%rowtype;o pet_egg_orders%rowtype;address text;paid_count int;begin select id into u from game_players where telegram_id=p_telegram_id;if u is null then raise exception'PLAYER_NOT_FOUND';end if;select*into o from pet_egg_orders where idempotency_key=p_idempotency_key;if o.id is not null then return jsonb_build_object('id',o.id,'paymentAddress',o.payment_address,'amountNano',o.amount_nano,'amountTon',o.price_ton,'paymentComment',o.payment_comment,'expiresAt',o.expires_at);end if;select*into e from pet_eggs where id=p_egg_id and is_enabled for share;if e.id is null or not e.is_purchasable or e.price_ton is null then raise exception'EGG_NOT_AVAILABLE_FOR_TON';end if;if e.daily_quantity is not null and(select count(*)from pet_egg_orders where egg_id=e.id and status in('paid','delivered')and created_at>=date_trunc('day',now()))>=e.daily_quantity then raise exception'DAILY_EGG_LIMIT_REACHED';end if;if e.per_player_limit is not null then select count(*)into paid_count from pet_egg_orders where egg_id=e.id and user_id=u and status in('paid','delivered');if paid_count>=e.per_player_limit then raise exception'PLAYER_EGG_LIMIT_REACHED';end if;end if;address:=wallet_hot_address();insert into pet_egg_orders(user_id,egg_id,price_ton,amount_nano,payment_address,payment_comment,idempotency_key)values(u,e.id,e.price_ton,round(e.price_ton*1000000000)::text,address,'forge_egg:'||gen_random_uuid(),p_idempotency_key)returning*into o;return jsonb_build_object('id',o.id,'paymentAddress',o.payment_address,'amountNano',o.amount_nano,'amountTon',o.price_ton,'paymentComment',o.payment_comment,'expiresAt',o.expires_at);end$$;

create or replace function public.confirm_wallet_deposit(p_deposit_id uuid,p_tx_hash text,p_amount_nano text)returns void language plpgsql security definer set search_path=public as $$declare d wallet_deposits%rowtype;begin select*into d from wallet_deposits where id=p_deposit_id for update;if d.id is null then raise exception'DEPOSIT_NOT_FOUND';end if;if d.status='credited'then return;end if;if d.expires_at<now()then update wallet_deposits set status='expired'where id=d.id;raise exception'DEPOSIT_EXPIRED';end if;if p_amount_nano<>round(d.amount_ton*1000000000)::text then raise exception'PAYMENT_AMOUNT_MISMATCH';end if;if exists(select 1 from wallet_deposits where tx_hash=p_tx_hash and id<>d.id)or exists(select 1 from pet_egg_orders where tx_hash=p_tx_hash)then raise exception'TX_ALREADY_USED';end if;update wallet_deposits set status='confirmed',tx_hash=p_tx_hash,confirmed_at=now()where id=d.id;update game_players set forge_coins=forge_coins+d.amount_fc,updated_at=now()where id=d.user_id;update wallet_deposits set status='credited',credited_at=now()where id=d.id;end$$;

create or replace function public.confirm_pet_egg_order(p_order_id uuid,p_tx_hash text,p_amount_nano text)returns void language plpgsql security definer set search_path=public as $$declare o pet_egg_orders%rowtype;begin select*into o from pet_egg_orders where id=p_order_id for update;if o.id is null then raise exception'ORDER_NOT_FOUND';end if;if o.status='delivered'then return;end if;if o.expires_at<now()then update pet_egg_orders set status='expired'where id=o.id;raise exception'ORDER_EXPIRED';end if;if p_amount_nano<>o.amount_nano then raise exception'PAYMENT_AMOUNT_MISMATCH';end if;if exists(select 1 from pet_egg_orders where tx_hash=p_tx_hash and id<>o.id)or exists(select 1 from wallet_deposits where tx_hash=p_tx_hash)then raise exception'TX_ALREADY_USED';end if;update pet_egg_orders set status='paid',tx_hash=p_tx_hash,paid_at=now()where id=o.id;insert into player_pet_inventory(user_id,item_type,item_id,quantity)values(o.user_id,'egg',o.egg_id,1)on conflict(user_id,item_type,(coalesce(item_id,'00000000-0000-0000-0000-000000000000'::uuid)))do update set quantity=player_pet_inventory.quantity+1,updated_at=now();update pet_egg_orders set status='delivered',delivered_at=now()where id=o.id;end$$;

create or replace function public.finish_wallet_withdrawal(p_withdrawal_id uuid,p_status text,p_tx_hash text default null)returns void language plpgsql security definer set search_path=public as $$declare w wallet_withdrawals%rowtype;begin if p_status not in('processing','completed','rejected','cancelled')then raise exception'INVALID_WITHDRAWAL_STATUS';end if;select*into w from wallet_withdrawals where id=p_withdrawal_id for update;if w.id is null then raise exception'WITHDRAWAL_NOT_FOUND';end if;if w.status in('completed','rejected','cancelled')then return;end if;if p_status in('rejected','cancelled')then update game_players set forge_coins=forge_coins+w.amount_fc,updated_at=now()where id=w.user_id;end if;update wallet_withdrawals set status=p_status,tx_hash=case when p_status='completed'then p_tx_hash else tx_hash end,processed_at=case when p_status in('completed','rejected','cancelled')then now()else processed_at end where id=w.id;end$$;

create or replace function public.get_wallet_summary(p_telegram_id bigint)returns jsonb language plpgsql security definer set search_path=public as $$
declare u game_players%rowtype;rate numeric;
begin
 select*into u from game_players where telegram_id=p_telegram_id;if u.id is null then raise exception'PLAYER_NOT_FOUND';end if;select value_numeric into rate from economy_settings where key='fc_per_ton';
 return jsonb_build_object('balanceFc',u.forge_coins,'equivalentTon',round(u.forge_coins/rate,4),
  'deposits',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'amountTon',amount_ton,'amountFc',amount_fc,'status',status,'createdAt',created_at)order by created_at desc),'[]')from(select*from wallet_deposits where user_id=u.id order by created_at desc limit 30)x),
  'withdrawals',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'amountFc',amount_fc,'amountTon',amount_ton,'status',status,'createdAt',created_at)order by created_at desc),'[]')from(select*from wallet_withdrawals where user_id=u.id order by created_at desc limit 30)x),
  'eggOrders',(select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'eggName',e.name,'priceTon',o.price_ton,'status',o.status,'createdAt',o.created_at)order by o.created_at desc),'[]')from(select*from pet_egg_orders where user_id=u.id order by created_at desc limit 30)o join pet_eggs e on e.id=o.egg_id),
  'history',(select coalesce(jsonb_agg(z order by created_at desc),'[]')from(
   select jsonb_build_object('id',id,'type','deposit','label','Deposito de '||amount_ton||' TON','amountFc',amount_fc,'amountTon',amount_ton,'status',status,'createdAt',created_at)z,created_at from wallet_deposits where user_id=u.id
   union all select jsonb_build_object('id',id,'type','withdrawal','label','Saque de '||amount_fc||' FC','amountFc',amount_fc,'amountTon',amount_ton,'status',status,'createdAt',created_at),created_at from wallet_withdrawals where user_id=u.id
   union all select jsonb_build_object('id',o.id,'type','egg_order','label',e.name,'amountFc',null,'amountTon',o.price_ton,'status',o.status,'createdAt',o.created_at),o.created_at from pet_egg_orders o join pet_eggs e on e.id=o.egg_id where o.user_id=u.id
   order by created_at desc limit 50)h));
end$$;

revoke all on function public.wallet_hot_address() from public,anon,authenticated;
revoke all on function public.get_wallet_summary(bigint) from public,anon,authenticated;
revoke all on function public.create_wallet_deposit(bigint,numeric,text,text) from public,anon,authenticated;
revoke all on function public.request_wallet_withdrawal(bigint,numeric,text,text) from public,anon,authenticated;
revoke all on function public.create_pet_egg_order(bigint,uuid,text) from public,anon,authenticated;
revoke all on function public.confirm_wallet_deposit(uuid,text,text) from public,anon,authenticated;
revoke all on function public.confirm_pet_egg_order(uuid,text,text) from public,anon,authenticated;
revoke all on function public.finish_wallet_withdrawal(uuid,text,text) from public,anon,authenticated;
grant execute on function public.get_wallet_summary(bigint),public.create_wallet_deposit(bigint,numeric,text,text),public.request_wallet_withdrawal(bigint,numeric,text,text),public.create_pet_egg_order(bigint,uuid,text),public.confirm_wallet_deposit(uuid,text,text),public.confirm_pet_egg_order(uuid,text,text),public.finish_wallet_withdrawal(uuid,text,text),public.wallet_hot_address() to service_role;