alter table pet_eggs add column if not exists is_purchasable boolean not null default true,add column if not exists premium_only boolean not null default false,add column if not exists daily_quantity integer check(daily_quantity is null or daily_quantity>=0),add column if not exists per_player_limit integer check(per_player_limit is null or per_player_limit>=0),add column if not exists availability_label text;

update pet_eggs set price_fc=25000,price_ton=null,rarity_rates='{"common":75,"uncommon":20,"rare":5}'::jsonb,is_purchasable=true,premium_only=false,availability_label=null,updated_at=now()where slug='common-egg';
update pet_eggs set price_fc=100000,price_ton=null,rarity_rates='{"common":35,"uncommon":40,"rare":20,"epic":5}'::jsonb,is_purchasable=true,premium_only=false,availability_label=null,updated_at=now()where slug='rare-egg';
update pet_eggs set price_fc=null,price_ton=3,rarity_rates='{"rare":45,"epic":45,"legendary":10}'::jsonb,is_purchasable=true,premium_only=true,availability_label='Premium',updated_at=now()where slug='epic-egg';
update pet_eggs set price_fc=null,price_ton=10,rarity_rates='{"rare":50,"epic":40,"legendary":10}'::jsonb,allowed_pet_categories='["dragon"]'::jsonb,is_purchasable=true,premium_only=true,availability_label='Loja Premium',updated_at=now()where slug='dragon-egg';
update pet_eggs set price_fc=null,price_ton=null,rarity_rates='{"epic":70,"legendary":30}'::jsonb,is_purchasable=false,premium_only=true,availability_label='Evento Exclusivo',updated_at=now()where slug='ancestral-egg';

create or replace function public.get_pet_egg_store(p_telegram_id bigint)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;begin select id into u from game_players where telegram_id=p_telegram_id;if u is null then raise exception 'PLAYER_NOT_FOUND';end if;return coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'name',e.name,'slug',e.slug,'image',e.image_url,'priceFc',e.price_fc,'priceTon',e.price_ton,'quantity',coalesce(i.quantity,0),'rarityRates',e.rarity_rates,'isPurchasable',e.is_purchasable,'premiumOnly',e.premium_only,'dailyQuantity',e.daily_quantity,'perPlayerLimit',e.per_player_limit,'availabilityLabel',e.availability_label)order by case e.slug when'common-egg'then 1 when'rare-egg'then 2 when'epic-egg'then 3 when'dragon-egg'then 4 else 5 end)from pet_eggs e left join player_pet_inventory i on i.user_id=u and i.item_type='egg'and i.item_id=e.id where e.is_enabled),'[]'::jsonb);end$$;

create or replace function public.admin_update_pet_egg_economy(p_egg_id uuid,p_price_fc numeric,p_price_ton numeric,p_rates jsonb,p_enabled boolean,p_daily_quantity integer,p_player_limit integer,p_purchasable boolean,p_premium_only boolean,p_label text)returns pet_eggs language plpgsql security definer set search_path=public as $$declare total numeric;result pet_eggs%rowtype;invalid_key boolean;begin if p_price_fc<0 or p_price_ton<0 or p_daily_quantity<0 or p_player_limit<0 then raise exception 'INVALID_EGG_ECONOMY_VALUE';end if;select coalesce(sum(value::text::numeric),0),coalesce(bool_or(key not in('common','uncommon','rare','epic','legendary')),false)into total,invalid_key from jsonb_each(p_rates);if total<>100 or invalid_key then raise exception 'INVALID_RARITY_RATES';end if;update pet_eggs set price_fc=p_price_fc,price_ton=p_price_ton,rarity_rates=p_rates,is_enabled=p_enabled,daily_quantity=p_daily_quantity,per_player_limit=p_player_limit,is_purchasable=p_purchasable,premium_only=p_premium_only,availability_label=nullif(trim(p_label),''),updated_at=now()where id=p_egg_id returning*into result;if result.id is null then raise exception 'EGG_NOT_FOUND';end if;return result;end$$;
grant execute on function get_pet_egg_store(bigint),admin_update_pet_egg_economy(uuid,numeric,numeric,jsonb,boolean,integer,integer,boolean,boolean,text)to service_role;
