create or replace function normalize_pet_rarity(v text) returns text language sql immutable as $$select case lower(trim(coalesce(v,'common'))) when 'uncommon' then 'uncommon' when 'incomum' then 'uncommon' when 'rare' then 'rare' when 'raro' then 'rare' when 'rara' then 'rare' when 'epic' then 'epic' when 'epico' then 'epic' when 'épico' then 'epic' when 'epica' then 'epic' when 'épica' then 'epic' when 'legendary' then 'legendary' when 'lendario' then 'legendary' when 'lendário' then 'legendary' when 'lendaria' then 'legendary' when 'lendária' then 'legendary' else 'common' end$$;
create or replace function pet_rarity_multiplier(v text) returns numeric language sql immutable as $$select case normalize_pet_rarity(v) when 'uncommon' then 1.25 when 'rare' then 1.6 when 'epic' then 2.1 when 'legendary' then 2.8 else 1 end$$;
create or replace function pet_evolution_stage(v int) returns text language sql immutable as $$select case when v>=30 then 'ancestral' when v>=20 then 'adult' when v>=10 then 'young' else 'baby' end$$;
create or replace function public.get_pet_bonuses(p_user uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r record;result jsonb:='{}';k text;base numeric;cap numeric;final numeric;begin select pp.rarity,pp.level,p.base_passives into r from player_pets pp join pets p on p.id=pp.pet_id where pp.user_id=p_user and pp.is_active;if not found then return result;end if;for k,base in select key,value::text::numeric from jsonb_each(r.base_passives) loop select (value->>k)::numeric into cap from pet_settings where key='bonus_caps';final:=round(base*pet_rarity_multiplier(r.rarity)*(1+(r.level-1)*.02),2);if cap is not null then final:=least(final,cap);end if;result:=result||jsonb_build_object(k,final);end loop;return result;end$$;
create or replace function public.activate_pet(p_telegram_id bigint,p_player_pet_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;pet player_pets%rowtype;old_hp numeric;new_hp numeric;begin select id into u from game_players where telegram_id=p_telegram_id for update;if u is null then raise exception 'PLAYER_NOT_FOUND';end if;select * into pet from player_pets where id=p_player_pet_id and user_id=u for update;if pet.id is null then raise exception 'PET_NOT_OWNED';end if;old_hp:=coalesce((get_pet_bonuses(u)->>'team_hp_percent')::numeric,0);update player_pets set is_active=false,updated_at=now() where user_id=u and is_active;update player_pets set is_active=true,updated_at=now() where id=pet.id;new_hp:=coalesce((get_pet_bonuses(u)->>'team_hp_percent')::numeric,0);update hero_combat_state h set current_hp=least(round(h.current_hp/nullif(1+old_hp/100,0)*(1+new_hp/100)),round(h.max_hp/nullif(1+old_hp/100,0)*(1+new_hp/100))),max_hp=round(h.max_hp/nullif(1+old_hp/100,0)*(1+new_hp/100)),updated_at=now() from boss_combats b where h.combat_id=b.id and b.user_id=u and b.status='active';return get_pet_dashboard(p_telegram_id);end$$;
create or replace function public.feed_pet(p_telegram_id bigint,p_player_pet_id uuid,p_food integer) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;pet player_pets%rowtype;available int;needed int;gain int;begin if p_food<1 or p_food>1000 then raise exception 'INVALID_FOOD_AMOUNT';end if;select id into u from game_players where telegram_id=p_telegram_id for update;select * into pet from player_pets where id=p_player_pet_id and user_id=u for update;if pet.id is null then raise exception 'PET_NOT_OWNED';end if;if pet.level>=30 then raise exception 'PET_MAX_LEVEL';end if;select quantity into available from player_pet_inventory where user_id=u and item_type='food' and item_id is null for update;if coalesce(available,0)<p_food then raise exception 'NOT_ENOUGH_PET_FOOD';end if;update player_pet_inventory set quantity=quantity-p_food,updated_at=now() where user_id=u and item_type='food' and item_id is null;gain:=p_food*100;pet.xp:=pet.xp+gain;while pet.level<30 loop needed:=round(250*power(pet.level,1.35));exit when pet.xp<needed;pet.xp:=pet.xp-needed;pet.level:=pet.level+1;end loop;if pet.level=30 then pet.xp:=0;end if;update player_pets set level=pet.level,xp=pet.xp,evolution_stage=pet_evolution_stage(pet.level),updated_at=now() where id=pet.id;return get_pet_dashboard(p_telegram_id);end$$;
create or replace function public.upgrade_pet(p_telegram_id bigint,p_player_pet_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;pet player_pets%rowtype;fc numeric;food int;frag int;have_food int;have_frag int;begin select id into u from game_players where telegram_id=p_telegram_id for update;select * into pet from player_pets where id=p_player_pet_id and user_id=u for update;if pet.id is null then raise exception 'PET_NOT_OWNED';end if;if pet.level>=30 then raise exception 'PET_MAX_LEVEL';end if;fc:=round(1000*power(pet.level,1.45));food:=ceil(pet.level/3.0);frag:=case when pet.level>=10 then ceil(pet.level/5.0) else 0 end;if(select forge_coins from game_players where id=u)<fc then raise exception 'NOT_ENOUGH_FC';end if;select quantity into have_food from player_pet_inventory where user_id=u and item_type='food' and item_id is null for update;select quantity into have_frag from player_pet_inventory where user_id=u and item_type='universal_fragment' and item_id is null for update;if coalesce(have_food,0)<food then raise exception 'NOT_ENOUGH_PET_FOOD';end if;if coalesce(have_frag,0)<frag and pet.fragments<frag then raise exception 'NOT_ENOUGH_FRAGMENTS';end if;update game_players set forge_coins=forge_coins-fc,updated_at=now() where id=u;update player_pet_inventory set quantity=quantity-food,updated_at=now() where user_id=u and item_type='food' and item_id is null;if frag>0 then if pet.fragments>=frag then pet.fragments:=pet.fragments-frag;else update player_pet_inventory set quantity=quantity-frag,updated_at=now() where user_id=u and item_type='universal_fragment' and item_id is null;end if;end if;update player_pets set level=level+1,fragments=pet.fragments,evolution_stage=pet_evolution_stage(level+1),updated_at=now() where id=pet.id;insert into pet_upgrade_history(user_id,player_pet_id,old_level,new_level,fc_spent,food_spent,fragments_spent) values(u,pet.id,pet.level,pet.level+1,fc,food,frag);return get_pet_dashboard(p_telegram_id);end$$;

create or replace function public.hatch_pet_egg(p_telegram_id bigint,p_egg_id uuid,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;egg pet_eggs%rowtype;inv player_pet_inventory%rowtype;seed bytea;seed_text text;roll numeric;cursor numeric:=0;k text;rate numeric;rar text:='common';picked pets%rowtype;existing player_pets%rowtype;frags int:=0;history_id uuid;luck numeric:=0;begin if length(trim(p_idempotency_key))<8 then raise exception 'INVALID_IDEMPOTENCY_KEY';end if;select id into u from game_players where telegram_id=p_telegram_id for update;if exists(select 1 from pet_hatch_history where idempotency_key=p_idempotency_key and user_id=u) then return get_pet_dashboard(p_telegram_id);end if;select * into egg from pet_eggs where id=p_egg_id and is_enabled;if egg.id is null then raise exception 'EGG_NOT_FOUND';end if;select * into inv from player_pet_inventory where user_id=u and item_type='egg' and item_id=p_egg_id for update;if inv.id is null or inv.quantity<1 then raise exception 'EGG_NOT_OWNED';end if;update player_pet_inventory set quantity=quantity-1,updated_at=now() where id=inv.id;seed:=gen_random_bytes(32);seed_text:=encode(digest(seed,'sha256'),'hex');luck:=least(10,coalesce((get_pet_bonuses(u)->>'egg_luck_percent')::numeric,0));roll:=least(99.999,(('x'||substr(seed_text,1,8))::bit(32)::bigint%1000000)/10000.0+luck);foreach k in array array['common','uncommon','rare','epic','legendary'] loop rate:=coalesce((egg.rarity_rates->>k)::numeric,0);cursor:=cursor+rate;if roll<cursor then rar:=k;exit;end if;end loop;select * into picked from pets p where p.is_enabled and (egg.allowed_pet_categories is null or egg.allowed_pet_categories ? p.category) order by hashtextextended(p.id::text||seed_text,0) limit 1;if picked.id is null then raise exception 'NO_ELIGIBLE_PET';end if;select * into existing from player_pets where user_id=u and pet_id=picked.id for update;if existing.id is not null then select coalesce((value->>rar)::int,10) into frags from pet_settings where key='duplicate_fragments';update player_pets set fragments=fragments+frags,updated_at=now() where id=existing.id;else insert into player_pets(user_id,pet_id,rarity) values(u,picked.id,rar);end if;insert into pet_hatch_history(user_id,egg_id,result_pet_id,result_rarity,duplicate_fragments,seed_hash,idempotency_key) values(u,egg.id,picked.id,rar,frags,seed_text,p_idempotency_key) returning id into history_id;return jsonb_build_object('result',jsonb_build_object('historyId',history_id,'petId',picked.id,'name',picked.name,'rarity',rar,'image',picked.image_baby_url,'duplicateFragments',frags),'dashboard',get_pet_dashboard(p_telegram_id));end$$;

create or replace function public.get_pet_dashboard(p_telegram_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;begin select id into u from game_players where telegram_id=p_telegram_id;if u is null then raise exception 'PLAYER_NOT_FOUND';end if;return jsonb_build_object('activePet',(select jsonb_build_object('id',pp.id,'petId',p.id,'name',p.name,'slug',p.slug,'species',p.species,'category',p.category,'rarity',pp.rarity,'level',pp.level,'xp',pp.xp,'xpRequired',round(250*power(pp.level,1.35)),'evolutionStage',pp.evolution_stage,'fragments',pp.fragments,'isActive',pp.is_active,'image',case pp.evolution_stage when 'ancestral' then p.image_ancestral_url when 'adult' then p.image_adult_url when 'young' then p.image_young_url else p.image_baby_url end,'passives',get_pet_bonuses(u),'power',(case pp.rarity when 'legendary' then 8000 when 'epic' then 4000 when 'rare' then 2000 when 'uncommon' then 1000 else 500 end)+pp.level*100+coalesce((select sum(value::text::numeric)*250 from jsonb_each(get_pet_bonuses(u))),0),'activeSkill',p.active_skill) from player_pets pp join pets p on p.id=pp.pet_id where pp.user_id=u and pp.is_active),
'playerPets',(select coalesce(jsonb_agg(jsonb_build_object('id',pp.id,'petId',p.id,'name',p.name,'slug',p.slug,'species',p.species,'category',p.category,'rarity',pp.rarity,'level',pp.level,'xp',pp.xp,'xpRequired',round(250*power(pp.level,1.35)),'evolutionStage',pp.evolution_stage,'fragments',pp.fragments,'isActive',pp.is_active,'image',case pp.evolution_stage when 'ancestral' then p.image_ancestral_url when 'adult' then p.image_adult_url when 'young' then p.image_young_url else p.image_baby_url end,'passives',(select coalesce(jsonb_object_agg(e.key,round(e.value::text::numeric*pet_rarity_multiplier(pp.rarity)*(1+(pp.level-1)*.02),2)),'{}') from jsonb_each(p.base_passives)e),'power',(case pp.rarity when 'legendary' then 8000 when 'epic' then 4000 when 'rare' then 2000 when 'uncommon' then 1000 else 500 end)+pp.level*100,'activeSkill',p.active_skill) order by pp.is_active desc,pp.level desc),'[]') from player_pets pp join pets p on p.id=pp.pet_id where pp.user_id=u),
'catalog',(select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'slug',p.slug,'species',p.species,'category',p.category,'description',p.description,'basePassives',p.base_passives,'activeSkill',p.active_skill,'images',jsonb_build_object('baby',p.image_baby_url,'young',p.image_young_url,'adult',p.image_adult_url,'ancestral',p.image_ancestral_url),'discovered',pp.id is not null,'bestRarity',pp.rarity,'bestLevel',pp.level) order by p.name),'[]') from pets p left join player_pets pp on pp.pet_id=p.id and pp.user_id=u where p.is_enabled),
'eggs',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'name',e.name,'slug',e.slug,'image',e.image_url,'priceFc',e.price_fc,'priceTon',e.price_ton,'quantity',coalesce(i.quantity,0),'rarityRates',e.rarity_rates) order by e.price_fc),'[]') from pet_eggs e left join player_pet_inventory i on i.item_id=e.id and i.user_id=u and i.item_type='egg' where e.is_enabled),
'inventory',jsonb_build_object('food',coalesce((select quantity from player_pet_inventory where user_id=u and item_type='food' and item_id is null),0),'universalFragments',coalesce((select quantity from player_pet_inventory where user_id=u and item_type='universal_fragment' and item_id is null),0)),
'history',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'eggName',e.name,'petName',p.name,'rarity',h.result_rarity,'duplicateFragments',h.duplicate_fragments,'createdAt',h.created_at) order by h.created_at desc),'[]') from(select * from pet_hatch_history where user_id=u order by created_at desc limit 50)h join pet_eggs e on e.id=h.egg_id left join pets p on p.id=h.result_pet_id),'bonuses',get_pet_bonuses(u),'balance',(select forge_coins from game_players where id=u));end$$;

create or replace function public.get_pet_pvp_snapshot(p_user uuid) returns jsonb language sql security definer set search_path=public as $$select coalesce((select jsonb_build_object('pet_id',pp.id,'pet_name',p.name,'rarity',pp.rarity,'level',pp.level,'passive_effects',get_pet_bonuses(p_user),'active_skill',p.active_skill,'skill_cooldown',coalesce((p.active_skill->>'cooldown_seconds')::int,(p.active_skill->>'pvp_turns')::int)) from player_pets pp join pets p on p.id=pp.pet_id where pp.user_id=p_user and pp.is_active),'{}')$$;
create or replace function public.calculate_pet_reward(p_user uuid,p_base numeric,p_kind text,p_eligible boolean) returns jsonb language plpgsql security definer set search_path=public as $$declare b jsonb;percent numeric:=0;final numeric;begin if p_base<0 or p_base::text in('NaN','Infinity','-Infinity') then raise exception 'INVALID_BASE_REWARD';end if;b:=get_pet_bonuses(p_user);if p_eligible then percent:=case p_kind when 'farm' then coalesce((b->>'farm_fc_percent')::numeric,0) when 'offline' then coalesce((b->>'offline_production_percent')::numeric,0) when 'mission' then coalesce((b->>'mission_reward_percent')::numeric,0) when 'hero_xp' then coalesce((b->>'hero_xp_percent')::numeric,0) when 'account_xp' then coalesce((b->>'account_xp_percent')::numeric,0) else 0 end;end if;final:=floor(p_base*(1+percent/100));return jsonb_build_object('base',p_base,'petBonusPercent',percent,'final',final,'eligible',p_eligible);end$$;
grant execute on function get_pet_dashboard(bigint),activate_pet(bigint,uuid),feed_pet(bigint,uuid,integer),upgrade_pet(bigint,uuid),hatch_pet_egg(bigint,uuid,text),get_pet_bonuses(uuid),get_pet_pvp_snapshot(uuid),calculate_pet_reward(uuid,numeric,text,boolean) to service_role;

alter table boss_combats add column if not exists pet_next_skill_at timestamptz;
create or replace function public.apply_pet_hp_on_combat_hero() returns trigger language plpgsql security definer set search_path=public as $$declare u uuid;bonus numeric:=0;factor numeric;begin select user_id into u from boss_combats where id=new.combat_id;bonus:=coalesce((get_pet_bonuses(u)->>'team_hp_percent')::numeric,0);factor:=1+bonus/100;new.max_hp:=round(new.max_hp*factor);new.current_hp:=least(new.max_hp,round(new.current_hp*factor));return new;end$$;
drop trigger if exists hero_pet_hp_before_insert on hero_combat_state;
create trigger hero_pet_hp_before_insert before insert on hero_combat_state for each row execute function apply_pet_hp_on_combat_hero();
create or replace function public.process_boss_combat(p_telegram_id bigint,p_now timestamptz default clock_timestamp()) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
 c boss_combats%rowtype;event_at timestamptz;special_at timestamptz;revive_event timestamptz;cutoff timestamptz;team_damage numeric;target hero_combat_state%rowtype;dealt numeric;hero_count int;cycles bigint;kill_cycles bigint;bonuses jsonb;damage_bonus numeric:=0;damage_reduction numeric:=0;revive_speed numeric:=0;pet_slug text;skill_at timestamptz;skill_damage numeric;
begin
 select * into c from boss_combats where id=ensure_boss_combat(p_telegram_id) for update;
 if c.status<>'active' then return get_boss_combat(p_telegram_id);end if;
 bonuses:=get_pet_bonuses(c.user_id);damage_bonus:=coalesce((bonuses->>'boss_damage_percent')::numeric,0);damage_reduction:=coalesce((bonuses->>'boss_damage_reduction_percent')::numeric,0);revive_speed:=least(90,coalesce((bonuses->>'revive_speed_percent')::numeric,0));
 select p.slug into pet_slug from player_pets pp join pets p on p.id=pp.pet_id where pp.user_id=c.user_id and pp.is_active;
 skill_at:=case when pet_slug='pyron' then coalesce(c.pet_next_skill_at,c.started_at+interval '60 seconds') else 'infinity'::timestamptz end;
 cutoff:=greatest(c.last_processed_at,least(p_now,c.last_processed_at+interval '7 days'));
 loop
  exit when c.boss_current_hp<=0;
  select min(revive_at) into revive_event from hero_combat_state where combat_id=c.id and not is_alive;
  special_at:=least(c.boss_next_attack_at,coalesce(revive_event,'infinity'),skill_at,cutoff);
  if c.next_hero_attack_at<=special_at then
   select coalesce(sum(final_atk),0)*(1+damage_bonus/100),count(*) into team_damage,hero_count from hero_combat_state where combat_id=c.id and slot is not null and is_alive;
   cycles:=floor(extract(epoch from(special_at-c.next_hero_attack_at))/10)::bigint+1;
   if team_damage>0 then kill_cycles:=ceil(c.boss_current_hp/team_damage)::bigint;if kill_cycles<=cycles then event_at:=c.next_hero_attack_at+make_interval(secs=>((kill_cycles-1)*10)::int);dealt:=c.boss_current_hp;c.total_damage_dealt:=c.total_damage_dealt+dealt;c.boss_current_hp:=0;c.status:='defeated';c.defeated_at:=event_at;c.next_hero_attack_at:=event_at+interval '10 seconds';exit;end if;dealt:=least(c.boss_current_hp,team_damage*cycles);c.boss_current_hp:=greatest(0,c.boss_current_hp-dealt);c.total_damage_dealt:=c.total_damage_dealt+dealt;end if;
   c.next_hero_attack_at:=c.next_hero_attack_at+make_interval(secs=>(cycles*10)::int);
  end if;
  exit when special_at>=cutoff;event_at:=special_at;
  update hero_combat_state set is_alive=true,current_hp=max_hp,knocked_out_at=null,revive_at=null,updated_at=event_at where combat_id=c.id and not is_alive and revive_at<=event_at;
  if skill_at<=event_at then select coalesce(sum(final_atk),0)*3 into skill_damage from hero_combat_state where combat_id=c.id and slot is not null and is_alive;if skill_damage>0 then dealt:=least(c.boss_current_hp,skill_damage);c.boss_current_hp:=c.boss_current_hp-dealt;c.total_damage_dealt:=c.total_damage_dealt+dealt;if c.boss_current_hp=0 then c.status:='defeated';c.defeated_at:=event_at;exit;end if;end if;skill_at:=skill_at+interval '60 seconds';end if;
  if c.boss_next_attack_at<=event_at then select * into target from hero_combat_state where combat_id=c.id and slot is not null and is_alive order by random() limit 1 for update;if found then target.current_hp:=greatest(0,target.current_hp-greatest(1,round(c.boss_attack*rarity_resistance(target.rarity)*(1-damage_reduction/100))));update hero_combat_state set current_hp=target.current_hp,is_alive=(target.current_hp>0),knocked_out_at=case when target.current_hp=0 then event_at end,revive_at=case when target.current_hp=0 then event_at+make_interval(secs=>round(300*(1-revive_speed/100))::int) end,updated_at=event_at where id=target.id;end if;c.boss_last_attack_at:=event_at;c.boss_next_attack_at:=c.boss_next_attack_at+make_interval(secs=>c.boss_attack_interval_seconds);end if;
 end loop;
 update boss_combats set boss_current_hp=c.boss_current_hp,total_damage_dealt=c.total_damage_dealt,status=c.status,defeated_at=c.defeated_at,last_processed_at=cutoff,next_hero_attack_at=c.next_hero_attack_at,boss_last_attack_at=c.boss_last_attack_at,boss_next_attack_at=c.boss_next_attack_at,pet_next_skill_at=case when pet_slug='pyron' then skill_at end,updated_at=clock_timestamp() where id=c.id;
 return get_boss_combat(p_telegram_id);
end$$;

create or replace function public.get_pet_admin_stats() returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('activePets',(select count(*) from player_pets where is_active),'eggsOpenedToday',(select count(*) from pet_hatch_history where created_at>=date_trunc('day',now())),'legendaryObtained',(select count(*) from player_pets where rarity='legendary'),'mostUsedPet',(select p.name from player_pets pp join pets p on p.id=pp.pet_id group by p.id order by count(*) filter(where pp.is_active) desc,count(*) desc limit 1),'fcSpentUpgrades',(select coalesce(sum(fc_spent),0) from pet_upgrade_history),'rarityDistribution',(select coalesce(jsonb_object_agg(rarity,total),'{}') from(select rarity,count(*) total from player_pets group by rarity)x))$$;
create or replace function public.admin_grant_pet_item(p_telegram_id bigint,p_item_type text,p_item_id uuid,p_quantity integer) returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;begin if p_item_type not in('egg','food','universal_fragment') or p_quantity=0 then raise exception 'INVALID_ITEM_GRANT';end if;select id into u from game_players where telegram_id=p_telegram_id for update;if u is null then raise exception 'PLAYER_NOT_FOUND';end if;if p_item_type='egg' and not exists(select 1 from pet_eggs where id=p_item_id) then raise exception 'EGG_NOT_FOUND';end if;insert into player_pet_inventory(user_id,item_type,item_id,quantity) values(u,p_item_type,case when p_item_type='egg' then p_item_id end,greatest(0,p_quantity)) on conflict(user_id,item_type,(coalesce(item_id,'00000000-0000-0000-0000-000000000000'::uuid))) do update set quantity=greatest(0,player_pet_inventory.quantity+p_quantity),updated_at=now();return get_pet_dashboard(p_telegram_id);end$$;
create or replace function public.admin_set_pet_enabled(p_pet_id uuid,p_enabled boolean) returns void language plpgsql security definer set search_path=public as $$begin update pets set is_enabled=p_enabled,updated_at=now() where id=p_pet_id;if not found then raise exception 'PET_NOT_FOUND';end if;end$$;
grant execute on function get_pet_admin_stats(),admin_grant_pet_item(bigint,text,uuid,integer),admin_set_pet_enabled(uuid,boolean) to service_role;