create table if not exists season_pass_seasons(id uuid primary key default gen_random_uuid(),name text not null,start_at timestamptz not null,end_at timestamptz not null,levels int not null default 30 check(levels between 1 and 100),xp_per_level int not null default 1000 check(xp_per_level>0),adventurer_price_ton numeric not null default 5,legendary_price_ton numeric not null default 20,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_at>start_at));
insert into season_pass_seasons(name,start_at,end_at)select'Temporada 1',now(),now()+interval'30 days'where not exists(select 1 from season_pass_seasons where active);
create unique index if not exists one_active_season on season_pass_seasons(active)where active;
create table if not exists season_pass_rewards(id uuid primary key default gen_random_uuid(),season_id uuid not null references season_pass_seasons(id)on delete cascade,level int not null check(level between 1 and 100),tier text not null check(tier in('free','adventurer','legendary')),reward_type text not null check(reward_type in('fc','hero_chest','pet_egg','pet_food','fragments','pvp_ticket','skin')),reward_code text,amount numeric not null default 1 check(amount>0),title text not null,enabled boolean not null default true,updated_at timestamptz not null default now(),unique(season_id,level,tier));
insert into season_pass_rewards(season_id,level,tier,reward_type,reward_code,amount,title)
select s.id,l,t.tier,case when t.tier='free'then case when l%5=0 then'pvp_ticket'else'fc'end when t.tier='adventurer'then case when l%5=0 then'fc'when l%3=0 then'hero_chest'when l%2=0 then'pet_food'else'fragments'end else case when l%3=0 then'fc'when l%5=0 then'pet_egg'when l%2=0 then'hero_chest'else'skin'end end,case when t.tier='adventurer'and l%3=0 then'hero_chest_improved'when t.tier='legendary'and l%5=0 then'rare-egg'when t.tier='legendary'and l%2=0 then'hero_chest_special'when t.tier='legendary'and l%3<>0 and l%5<>0 and l%2<>0 then'forgemaster-cosmetic'else null end,case when t.tier='free'then case when l%5=0 then 1 else 1000 end when t.tier='adventurer'then case when l%5=0 then 20000 when l%2=0 then 5 else 10 end else case when l%3=0 then 40000 else 1 end end,case when t.tier='free'then case when l%5=0 then'Ticket PvP'else'1.000 FC'end when t.tier='adventurer'then case when l%5=0 then'20.000 FC'when l%3=0 then'Baú Aprimorado'when l%2=0 then'Comida de Pet'else'Fragmentos'end else case when l%3=0 then'40.000 FC'when l%5=0 then'Ovo Raro'when l%2=0 then'Baú Especial'else'Skin da Forja'end end from season_pass_seasons s cross join generate_series(1,30)l cross join(values('free'),('adventurer'),('legendary'))t(tier)where s.active on conflict do nothing;
create table if not exists player_season_pass(user_id uuid not null references game_players(id),season_id uuid not null references season_pass_seasons(id),xp int not null default 0 check(xp>=0),adventurer_owned boolean not null default false,legendary_owned boolean not null default false,updated_at timestamptz not null default now(),primary key(user_id,season_id));
create table if not exists season_pass_claims(id uuid primary key default gen_random_uuid(),user_id uuid not null references game_players(id),reward_id uuid not null references season_pass_rewards(id),idempotency_key text unique not null,claimed_at timestamptz not null default now(),unique(user_id,reward_id));
create table if not exists season_pass_orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references game_players(id),season_id uuid not null references season_pass_seasons(id),tier text not null check(tier in('adventurer','legendary')),price_ton numeric not null,amount_nano text not null,payment_address text not null,payment_comment text not null,status text not null default'pending'check(status in('pending','paid','activated','expired','cancelled')),tx_hash text unique,idempotency_key text unique not null,created_at timestamptz not null default now(),paid_at timestamptz,activated_at timestamptz,expires_at timestamptz not null default now()+interval'15 minutes');
grant all on season_pass_seasons to service_role;
grant all on season_pass_rewards to service_role;
grant all on player_season_pass to service_role;
grant all on season_pass_claims to service_role;
grant all on season_pass_orders to service_role;
revoke all on season_pass_seasons,season_pass_rewards,player_season_pass,season_pass_claims,season_pass_orders from anon,authenticated;
alter table season_pass_seasons enable row level security;alter table season_pass_rewards enable row level security;alter table player_season_pass enable row level security;alter table season_pass_claims enable row level security;alter table season_pass_orders enable row level security;

create or replace function get_season_pass_dashboard(p_telegram_id bigint)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;s season_pass_seasons%rowtype;p player_season_pass%rowtype;begin select id into u from game_players where telegram_id=p_telegram_id;select*into s from season_pass_seasons where active and now()between start_at and end_at;if u is null or s.id is null then raise exception'SEASON_NOT_AVAILABLE';end if;insert into player_season_pass(user_id,season_id)values(u,s.id)on conflict do nothing;select*into p from player_season_pass where user_id=u and season_id=s.id;return jsonb_build_object('season',jsonb_build_object('id',s.id,'name',s.name,'endsAt',s.end_at,'levels',s.levels,'xpPerLevel',s.xp_per_level,'adventurerPriceTon',s.adventurer_price_ton,'legendaryPriceTon',s.legendary_price_ton),'player',jsonb_build_object('xp',p.xp,'level',least(s.levels,floor(p.xp/s.xp_per_level)::int+1),'adventurerOwned',p.adventurer_owned or p.legendary_owned,'legendaryOwned',p.legendary_owned),'rewards',(select jsonb_agg(jsonb_build_object('id',r.id,'level',r.level,'tier',r.tier,'type',r.reward_type,'code',r.reward_code,'amount',r.amount,'title',r.title,'claimed',c.id is not null,'unlocked',r.level<=least(s.levels,floor(p.xp/s.xp_per_level)::int+1)and(r.tier='free'or r.tier='adventurer'and(p.adventurer_owned or p.legendary_owned)or r.tier='legendary'and p.legendary_owned))order by r.level,case r.tier when'free'then 1 when'adventurer'then 2 else 3 end)from season_pass_rewards r left join season_pass_claims c on c.reward_id=r.id and c.user_id=u where r.season_id=s.id and r.enabled));end$$;

create or replace function create_season_pass_order(p_telegram_id bigint,p_tier text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;s season_pass_seasons%rowtype;o season_pass_orders%rowtype;price numeric;address text;begin if p_tier not in('adventurer','legendary')then raise exception'INVALID_PASS_TIER';end if;select id into u from game_players where telegram_id=p_telegram_id;select*into s from season_pass_seasons where active and now()between start_at and end_at;if u is null or s.id is null then raise exception'SEASON_NOT_AVAILABLE';end if;select*into o from season_pass_orders where idempotency_key=p_idempotency_key;if o.id is not null then return jsonb_build_object('id',o.id,'paymentAddress',o.payment_address,'amountNano',o.amount_nano,'amountTon',o.price_ton,'paymentComment',o.payment_comment,'expiresAt',o.expires_at);end if;price:=case p_tier when'adventurer'then s.adventurer_price_ton else s.legendary_price_ton end;address:=wallet_hot_address();insert into season_pass_orders(user_id,season_id,tier,price_ton,amount_nano,payment_address,payment_comment,idempotency_key)values(u,s.id,p_tier,price,round(price*1000000000)::text,address,'forge_pass:'||gen_random_uuid(),p_idempotency_key)returning*into o;return jsonb_build_object('id',o.id,'paymentAddress',o.payment_address,'amountNano',o.amount_nano,'amountTon',o.price_ton,'paymentComment',o.payment_comment,'expiresAt',o.expires_at);end$$;

create or replace function confirm_season_pass_order(p_order_id uuid,p_tx_hash text,p_amount_nano text)returns void language plpgsql security definer set search_path=public as $$declare o season_pass_orders%rowtype;begin select*into o from season_pass_orders where id=p_order_id for update;if o.id is null then raise exception'ORDER_NOT_FOUND';end if;if o.status='activated'then return;end if;if o.expires_at<now()or o.amount_nano<>p_amount_nano then raise exception'INVALID_OR_EXPIRED_PAYMENT';end if;if exists(select 1 from season_pass_orders where tx_hash=p_tx_hash and id<>o.id)then raise exception'TX_ALREADY_USED';end if;update season_pass_orders set status='paid',tx_hash=p_tx_hash,paid_at=now()where id=o.id;insert into player_season_pass(user_id,season_id,adventurer_owned,legendary_owned)values(o.user_id,o.season_id,true,o.tier='legendary')on conflict(user_id,season_id)do update set adventurer_owned=true,legendary_owned=player_season_pass.legendary_owned or excluded.legendary_owned,updated_at=now();update season_pass_orders set status='activated',activated_at=now()where id=o.id;end$$;

create or replace function claim_season_pass_reward(p_telegram_id bigint,p_reward_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare u game_players%rowtype;r season_pass_rewards%rowtype;p player_season_pass%rowtype;s season_pass_seasons%rowtype;egg uuid;key text;begin select*into u from game_players where telegram_id=p_telegram_id for update;select*into r from season_pass_rewards where id=p_reward_id and enabled;select*into s from season_pass_seasons where id=r.season_id and active;select*into p from player_season_pass where user_id=u.id and season_id=s.id for update;if u.id is null or r.id is null or r.level>least(s.levels,floor(p.xp/s.xp_per_level)::int+1)then raise exception'REWARD_LOCKED';end if;if r.tier='adventurer'and not(p.adventurer_owned or p.legendary_owned)or r.tier='legendary'and not p.legendary_owned then raise exception'PASS_NOT_OWNED';end if;key:='season_reward:'||u.id||':'||r.id;insert into season_pass_claims(user_id,reward_id,idempotency_key)values(u.id,r.id,key)on conflict do nothing;if not found then return get_season_pass_dashboard(p_telegram_id);end if;if r.reward_type='fc'then update game_players set forge_coins=forge_coins+r.amount,updated_at=now()where id=u.id;elsif r.reward_type='pvp_ticket'then update game_players set pvp_tickets=pvp_tickets+r.amount::int,updated_at=now()where id=u.id;elsif r.reward_type='pet_egg'then select id into egg from pet_eggs where slug=r.reward_code;insert into player_pet_inventory(user_id,item_type,item_id,quantity)values(u.id,'egg',egg,r.amount::int)on conflict(user_id,item_type,(coalesce(item_id,'00000000-0000-0000-0000-000000000000'::uuid)))do update set quantity=player_pet_inventory.quantity+excluded.quantity,updated_at=now();elsif r.reward_type='pet_food'then insert into player_pet_inventory(user_id,item_type,quantity)values(u.id,'food',r.amount::int)on conflict(user_id,item_type,(coalesce(item_id,'00000000-0000-0000-0000-000000000000'::uuid)))do update set quantity=player_pet_inventory.quantity+excluded.quantity,updated_at=now();else insert into player_inventory(user_id,item_type,item_code,quantity)values(u.id,r.reward_type,coalesce(r.reward_code,r.reward_type),r.amount::int)on conflict(user_id,item_type,item_code)do update set quantity=player_inventory.quantity+excluded.quantity,updated_at=now();end if;return get_season_pass_dashboard(p_telegram_id);end$$;

create or replace function admin_update_season_pass(p_season_id uuid,p_name text,p_start_at timestamptz,p_end_at timestamptz,p_levels int,p_xp_per_level int,p_adventurer_price numeric,p_legendary_price numeric,p_active boolean)returns void language plpgsql security definer set search_path=public as $$begin if p_end_at<=p_start_at or p_levels not between 1 and 100 or p_xp_per_level<=0 or p_adventurer_price<=0 or p_legendary_price<=0 then raise exception'INVALID_SEASON_CONFIG';end if;if p_active then update season_pass_seasons set active=false where id<>p_season_id and active;end if;update season_pass_seasons set name=trim(p_name),start_at=p_start_at,end_at=p_end_at,levels=p_levels,xp_per_level=p_xp_per_level,adventurer_price_ton=p_adventurer_price,legendary_price_ton=p_legendary_price,active=p_active,updated_at=now()where id=p_season_id;if not found then raise exception'SEASON_NOT_FOUND';end if;end$$;

create or replace function admin_update_season_reward(p_reward_id uuid,p_level int,p_type text,p_code text,p_amount numeric,p_title text,p_enabled boolean)returns void language plpgsql security definer set search_path=public as $$begin if p_level<1 or p_amount<=0 or p_type not in('fc','hero_chest','pet_egg','pet_food','fragments','pvp_ticket','skin')then raise exception'INVALID_REWARD_CONFIG';end if;update season_pass_rewards set level=p_level,reward_type=p_type,reward_code=nullif(trim(p_code),''),amount=p_amount,title=trim(p_title),enabled=p_enabled,updated_at=now()where id=p_reward_id;if not found then raise exception'REWARD_NOT_FOUND';end if;end$$;

revoke all on function get_season_pass_dashboard(bigint),create_season_pass_order(bigint,text,text),confirm_season_pass_order(uuid,text,text),claim_season_pass_reward(bigint,uuid),admin_update_season_pass(uuid,text,timestamptz,timestamptz,int,int,numeric,numeric,boolean),admin_update_season_reward(uuid,int,text,text,numeric,text,boolean)from public,anon,authenticated;
grant execute on function get_season_pass_dashboard(bigint),create_season_pass_order(bigint,text,text),confirm_season_pass_order(uuid,text,text),claim_season_pass_reward(bigint,uuid),admin_update_season_pass(uuid,text,timestamptz,timestamptz,int,int,numeric,numeric,boolean),admin_update_season_reward(uuid,int,text,text,numeric,text,boolean)to service_role;