alter table player_heroes add column if not exists is_season_exclusive boolean not null default false,add column if not exists exclusive_season_id uuid references season_pass_seasons(id),add column if not exists exclusive_pass_tier text,add column if not exists exclusive_badge text,add column if not exists exclusive_passive jsonb not null default'{}',add column if not exists tradable boolean not null default true;
alter table pets add column if not exists is_season_exclusive boolean not null default false,add column if not exists exclusive_season_id uuid references season_pass_seasons(id),add column if not exists exclusive_pass_tier text,add column if not exists exclusive_badge text,add column if not exists exclusive_passive jsonb not null default'{}';
alter table player_pets add column if not exists is_season_exclusive boolean not null default false,add column if not exists exclusive_season_id uuid references season_pass_seasons(id),add column if not exists exclusive_badge text,add column if not exists tradable boolean not null default true;
alter table player_inventory add column if not exists is_exclusive boolean not null default false,add column if not exists season_id uuid references season_pass_seasons(id),add column if not exists pass_tier text,add column if not exists exclusive_reward_code text,add column if not exists tradable boolean not null default true;
create table if not exists season_exclusive_rewards(id uuid primary key default gen_random_uuid(),season_id uuid not null references season_pass_seasons(id),pass_tier text not null check(pass_tier in('adventurer','legendary')),reward_kind text not null check(reward_kind in('hero','mythic_egg')),reward_code text not null,display_name text not null,image_url text not null,badge text not null,passive jsonb not null default'{}',target_pet_id uuid references pets(id),enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(season_id,pass_tier),unique(season_id,reward_code));
create table if not exists season_exclusive_deliveries(id uuid primary key default gen_random_uuid(),season_id uuid not null references season_pass_seasons(id),user_id uuid not null references game_players(id),reward_id uuid not null references season_exclusive_rewards(id),delivery_kind text not null,idempotency_key text unique not null,created_at timestamptz not null default now(),unique(season_id,user_id,reward_id,delivery_kind));
grant all on season_exclusive_rewards,season_exclusive_deliveries to service_role;
revoke all on season_exclusive_rewards,season_exclusive_deliveries from anon,authenticated;
alter table season_exclusive_rewards enable row level security;alter table season_exclusive_deliveries enable row level security;

insert into pets(name,slug,species,category,description,base_passives,active_skill,image_baby_url,image_young_url,image_adult_url,image_ancestral_url,is_season_exclusive,exclusive_pass_tier,exclusive_badge,exclusive_passive,is_enabled)values('Drakoryn, Dragão Celestial','season-1-drakoryn','celestial_dragon','dragon','Pet exclusivo do Passe Lendário — Temporada 1','{"boss_damage_percent":6,"team_hp_percent":4,"pet_xp_percent":3,"pool_points_percent":2}','{"name":"Chama Celestial","pvp_turns":5,"average_team_atk_percent":70,"team_max_hp_shield_percent":4}','/assets/game/pets/pyron.webp','/assets/game/pets/pyron.webp','/assets/game/pets/pyron.webp','/assets/game/pets/pyron.webp',true,'legendary','EXCLUSIVO LENDÁRIO','{"aura":"Aura Celestial"}',false)on conflict(slug)do update set base_passives=excluded.base_passives,active_skill=excluded.active_skill,is_season_exclusive=true,is_enabled=false;
insert into season_exclusive_rewards(season_id,pass_tier,reward_kind,reward_code,display_name,image_url,badge,passive,target_pet_id)select s.id,'adventurer','hero','season-1-aldren','Aldren, Guardião da Forja','/assets/game/heroes/season-1-aldren.png','EXCLUSIVO DO PASSE','{"name":"Bênção do Aventureiro","hero_xp_percent":4,"boss_damage_percent":3,"mission_fc_percent":2}',null from season_pass_seasons s where s.name='Temporada 1'on conflict do nothing;
insert into season_exclusive_rewards(season_id,pass_tier,reward_kind,reward_code,display_name,image_url,badge,passive,target_pet_id)select s.id,'legendary','mythic_egg','season-1-mythic-egg','Ovo Mítico','/assets/game/pet-eggs/season-1-mythic-egg.png','EXCLUSIVO LENDÁRIO','{"contains":"Drakoryn, Dragão Celestial"}',p.id from season_pass_seasons s join pets p on p.slug='season-1-drakoryn'where s.name='Temporada 1'on conflict do nothing;
update season_pass_rewards r set reward_type=case e.reward_kind when'hero'then'hero_chest'else'skin'end,reward_code=e.reward_code,amount=1,title=case e.reward_kind when'hero'then'HERÓI EXCLUSIVO · Aldren'else'OVO MÍTICO · Pet Lendário exclusivo'end,updated_at=now()from season_exclusive_rewards e where r.season_id=e.season_id and r.tier=e.pass_tier and r.level=(select levels from season_pass_seasons where id=r.season_id);

create or replace function deliver_season_exclusive()returns trigger language plpgsql security definer set search_path=public as $$declare r season_pass_rewards%rowtype;e season_exclusive_rewards%rowtype;h uuid;k text;begin select*into r from season_pass_rewards where id=new.reward_id;select*into e from season_exclusive_rewards where season_id=r.season_id and pass_tier=r.tier and reward_code=r.reward_code and enabled;if e.id is null then return new;end if;k:=case e.reward_kind when'hero'then'season_pass_exclusive_hero:'else'season_pass_mythic_egg:'end||e.season_id||':'||new.user_id||':'||e.pass_tier;insert into season_exclusive_deliveries(season_id,user_id,reward_id,delivery_kind,idempotency_key)values(e.season_id,new.user_id,e.id,e.reward_kind,k)on conflict do nothing;if not found then return new;end if;if e.reward_kind='hero'then insert into player_heroes(user_id,hero_key,name,image,rarity,level,base_atk,base_hp,is_season_exclusive,exclusive_season_id,exclusive_pass_tier,exclusive_badge,exclusive_passive,tradable)values(new.user_id,e.reward_code,e.display_name,e.image_url,'epic',1,210,2200,true,e.season_id,'adventurer',e.badge,e.passive,false);else insert into player_inventory(user_id,item_type,item_code,quantity,is_exclusive,season_id,pass_tier,exclusive_reward_code,tradable)values(new.user_id,'pet_egg',e.reward_code,1,true,e.season_id,'legendary',e.reward_code,false)on conflict(user_id,item_type,item_code)do nothing;end if;return new;end$$;
drop trigger if exists season_exclusive_claim on season_pass_claims;
create trigger season_exclusive_claim after insert on season_pass_claims for each row execute function deliver_season_exclusive();

create or replace function open_season_mythic_egg(p_telegram_id bigint,p_item_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare u uuid;i player_inventory%rowtype;e season_exclusive_rewards%rowtype;existing uuid;k text;pp uuid;begin select id into u from game_players where telegram_id=p_telegram_id for update;select*into i from player_inventory where id=p_item_id and user_id=u and is_exclusive and item_type='pet_egg'and quantity>0 for update;if i.id is null then raise exception'MYTHIC_EGG_NOT_OWNED';end if;select*into e from season_exclusive_rewards where season_id=i.season_id and reward_code=i.exclusive_reward_code and reward_kind='mythic_egg'and enabled;k:='season_pass_exclusive_pet:'||e.season_id||':'||u||':legendary';select id into existing from season_exclusive_deliveries where idempotency_key=k;if existing is not null then raise exception'MYTHIC_EGG_ALREADY_OPENED';end if;update player_inventory set quantity=quantity-1 where id=i.id;insert into player_pets(user_id,pet_id,rarity,level,xp,evolution_stage,is_season_exclusive,exclusive_season_id,exclusive_badge,tradable)values(u,e.target_pet_id,'legendary',1,0,'baby',true,e.season_id,e.badge,false)returning id into pp;insert into season_exclusive_deliveries(season_id,user_id,reward_id,delivery_kind,idempotency_key)values(e.season_id,u,e.id,'pet',k);return jsonb_build_object('playerPetId',pp,'petId',e.target_pet_id,'name',e.display_name,'rarity','legendary','level',1,'xp',0,'evolutionStage','baby','badge',e.badge,'image',e.image_url);end$$;
revoke all on function open_season_mythic_egg(bigint,uuid)from public,anon,authenticated;grant execute on function open_season_mythic_egg(bigint,uuid)to service_role;